### ISSUE TITLE
Tool configuration assistant incompatible with julia 1.1.1.

### ISSUE THREAD

**Issue by mdandreadtu** [Spine-project/Spine-Toolbox#1]
The **tool configuration assistant** is unable to run and return this error:
"_SpineModel.jl requires Julia version 1.x, whereas current version is 1.1.1._"
I'm using julia 1.1.1 | Spine Toolbox v0.2.4 | spinedatabase_api v0.0.27 |Python 3.7.1 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10

**Comment by manuelma** [comment]
thanks for reporting. Apparently I didn't want to support julia higher than 1.1.0 for some reason. Now it's fixed, you can try pulling last dev and it should go through. Please let me know how it works.

**Comment by mdandreadtu** [comment]
it install correctly spine model but freeze during the installation of PyCall. This message is returned:

**Comment by manuelma** [comment]
The method was indeed missing. I added it in the last dev. Please try again whenever you have the chance and let me know?

**Comment by mdandreadtu** [comment]
it install PyCall now but after the installation is completed it asks again to install it.

**Comment by ererkka** [comment]
Is this still an open issue?

**Comment by manuelma** [comment]
@mdandreadtu what do you think? Have you tried with the last version from the dev branch? Please, can you provide details about your environment? Julia version, SpineToolbox version, and so on?

**Comment by mdandreadtu** [comment]
when I try to open spinetoolbox this error message is returned:
```
(spinetoolbox) C:\Users\Matteo\Spine-Toolbox\spinetoolbox>python spinetoolbox.py
Traceback (most recent call last):
  File "spinetoolbox.py", line 30, in <module>
    from ui_main import ToolboxUI
  File "C:\Users\Matteo\Spine-Toolbox\spinetoolbox\ui_main.py", line 39, in <module>
    from widgets.custom_menus import (
  File "C:\Users\Matteo\Spine-Toolbox\spinetoolbox\widgets\custom_menus.py", line 25, in <module>
    from plotting import plot_pivot_column, plot_selection, PlottingError, PivotTablePlottingHints
  File "C:\Users\Matteo\Spine-Toolbox\spinetoolbox\plotting.py", line 28, in <module>
    from spinedb_api import from_database, ParameterValueFormatError, TimeSeries
ImportError: cannot import name 'from_database' from 'spinedb_api' (C:\Users\Matteo\Anaconda3\envs\spinetoolbox\lib\site-packages\spinedb_api\__init__.py)

```

**Comment by ererkka** [comment]
Could you check the Spine DB API version you have by running

    python -c "import spinedb_api; print(spinedb_api.__version__)"

at the console. If it’s less than 0.0.36, please update by running

    pip install -U git+https://github.com/Spine-project/Spine-Database-API.git#egg=spinedb_api

**Comment by mdandreadtu** [comment]
it was lower so I updated it. When I try to open spinetoolbox it returns:
```
(spinetoolbox) C:\Users\Matteo\Spine-Toolbox\spinetoolbox>python spinetoolbox.py
Traceback (most recent call last):
  File "spinetoolbox.py", line 30, in <module>
    from ui_main import ToolboxUI
  File "C:\Users\Matteo\Spine-Toolbox\spinetoolbox\ui_main.py", line 39, in <module>
    from widgets.custom_menus import (
  File "C:\Users\Matteo\Spine-Toolbox\spinetoolbox\widgets\custom_menus.py", line 25, in <module>
    from plotting import plot_pivot_column, plot_selection, PlottingError, PivotTablePlottingHints
  File "C:\Users\Matteo\Spine-Toolbox\spinetoolbox\plotting.py", line 29, in <module>
    from widgets.plot_widget import PlotWidget
  File "C:\Users\Matteo\Spine-Toolbox\spinetoolbox\widgets\plot_widget.py", line 22, in <module>
    from .plot_canvas import PlotCanvas
  File "C:\Users\Matteo\Spine-Toolbox\spinetoolbox\widgets\plot_canvas.py", line 23, in <module>
    from pandas.plotting import register_matplotlib_converters
ModuleNotFoundError: No module named 'pandas'
```

**Comment by ererkka** [comment]
Which version of the Toolbox are you using? You can check the active git commit by e.g. `git describe`.

Seems that you might not have all dependencies installed. Please run

    pip install -r requirements.txt

to install all required Python libraries. (see instructions in [README](https://github.com/Spine-project/Spine-Toolbox/#installing-requirements)).

**Comment by mdandreadtu** [comment]
I can now open Spine-Toolbox  and succesfully install PyCall using the tool configuration assistant. It then ask again to install PyCall  infinitely 
`[10-09-2019 10:23:44] 	Starting program C:/Users/Matteo/AppData/Local/Julia-1.2.0/bin/julia.exe
[10-09-2019 10:23:44] 	Arguments: --project=@. -e using Pkg; Pkg.add(ARGS[1]); PyCall
[10-09-2019 10:23:44] 	Execution is in progress. See Process Log for messages (stdout&stderr)
[10-09-2019 10:24:43] 	Starting program C:/Users/Matteo/AppData/Local/Julia-1.2.0/bin/julia.exe
[10-09-2019 10:24:43] 	Arguments: --project=@. -e using Pkg; Pkg.add(ARGS[1]); PyCall
[10-09-2019 10:24:43] 	Execution is in progress. See Process Log for messages (stdout&stderr)
![a12](https://user-images.githubusercontent.com/51364710/64598228-aa3b4e00-d3b7-11e9-9902-1c99bb900e5c.PNG)

**Comment by ererkka** [comment]
So the Toolbox keeps trying to install `PyCall` popping up this dialog over and over again, is that right?

**Comment by mdandreadtu** [comment]
Correct

**Comment by ererkka** [comment]
Any ideas @manuelma?

**Comment by manuelma** [comment]
Yes, sorry for the trouble and thanks for reporting @mdandreadtu 

I suspect what happening is the following: after installing PyCall, the toolbox checks installation was successful by attempting to import PyCall. If this fails, it asks to install PyCall... hence the infinite loop.

What I will do now is break the loop and print out the error at importing PyCall. In this way we will now what's happening. I'll let you know as soon as I do it.

**Comment by PekkaSavolainen** [comment]
I just tried the whole process by installing Julia 1.2 and then opening the Tool configuration assistant and it seems to work fine on my computer.

![successful_spine_model_configuration](https://user-images.githubusercontent.com/43600314/64610614-48d7a700-d3d8-11e9-9d95-a4b972fa056f.png)

I did run a Julia Tool (template) before running the Tool configuration assistant, which installed IJulia automatically and then executed the Tool template.

I did find one problem, when running the Tool configuration assistant, the Event Log says that, **see Process Log for messages** but you cannot open the Process log since the Tool configuration window is application modal.

**Comment by mdandreadtu** [comment]
I have donwloaded now julia 1.2 as well, do I have to install the packages as said in the ReadME file in Spine-Model [https://github.com/Spine-project/Spine-Model#spinemodeljl](url) ?

**Comment by manuelma** [comment]
Latest dev has the fix I described above. That is, instead of attempting to install PyCall a second time, the assistant will stop and printout the error message. Please try it out whenever you have the chance @mdandreadtu --better if you don't manually install the other packages mentioned in SpineModel's README.

**Comment by mdandreadtu** [comment]
Hey, @manuelma i tried again and now it doesn't ask anymore to install 
PyCall. However it printed another error.

`Configuring SpineModel... This operation can take a few moments...
SpineModel is correctly installed.
Installing PyCall. This operation can take a few moments...
PyCall successfully installed.
Unable to determine the python program used by PyCall: ERROR: LoadError: LoadError: could not load library "C:\Users\Matteo\.julia\conda\3\python36.dll"
The specified module could not be found.
Stacktrace:
 [1] #dlopen#3(::Bool, ::typeof(Libdl.dlopen), ::String, ::UInt32) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Libdl\src\Libdl.jl:109
 [2] dlopen(::String, ::UInt32) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Libdl\src\Libdl.jl:109
 [3] top-level scope at C:\Users\Matteo\.julia\packages\PyCall\ttONZ\src\startup.jl:47
 [4] include at .\boot.jl:328 [inlined]
 [5] include_relative(::Module, ::String) at .\loading.jl:1094
 [6] include at .\Base.jl:31 [inlined]
 [7] include(::String) at C:\Users\Matteo\.julia\packages\PyCall\ttONZ\src\PyCall.jl:1
 [8] top-level scope at C:\Users\Matteo\.julia\packages\PyCall\ttONZ\src\PyCall.jl:41
 [9] include at .\boot.jl:328 [inlined]
 [10] include_relative(::Module, ::String) at .\loading.jl:1094
 [11] include(::Module, ::String) at .\Base.jl:31
 [12] top-level scope at none:2
 [13] eval at .\boot.jl:330 [inlined]
 [14] eval(::Expr) at .\client.jl:432
 [15] top-level scope at .\none:3
in expression starting at C:\Users\Matteo\.julia\packages\PyCall\ttONZ\src\startup.jl:41
in expression starting at C:\Users\Matteo\.julia\packages\PyCall\ttONZ\src\PyCall.jl:41
ERROR: Failed to precompile PyCall [438e738f-606a-5dbb-bf0a-cddfbfd45ab0] to C:\Users\Matteo\.julia\compiled\v1.2\PyCall\GkzkC.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1253
 [3] _require(::Base.PkgId) at .\loading.jl:1013
 [4] require(::Base.PkgId) at .\loading.jl:911
 [5] require(::Module, ::Symbol) at .\loading.jl:906.`

**Comment by ererkka** [comment]
What do you have in dir `C:\Users\Matteo\.julia\conda\3\python36.dll`?

**Comment by mdandreadtu** [comment]
The folder "3" in C:\Users\Matteo\.julia\conda\3 is empty

**Comment by ererkka** [comment]
Seems that your `PyCall` installation is for some reason incomplete. See this line in the error:

    Unable to determine the python program used by PyCall: ERROR: LoadError: LoadError: could not load library "C:\Users\Matteo\.julia\conda\3\python36.dll"

On Windows, `PyCall` defaults to installing its own Python interpreter with `Conda` package and it should be under *%USERPROFILE%\\.julia\conda\3*.

**Comment by mdandreadtu** [comment]
is there anything I can do to solve this issue?

**Comment by manuelma** [comment]
> is there anything I can do to solve this issue?

Sure, try and install PyCall manually from a live julia session, checkout instructions in https://github.com/JuliaPy/PyCall.jl

**Comment by PekkaSavolainen** [comment]
Configuration Assistant for SpineOpt.jl has been revised since this issue was last active so the error descriptions above are obsolete. Please open a new issue if this is still a problem.
