### ISSUE TITLE
"main_includes_path" could be relative

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1231]
At the moment it is impossible to relocate a project folder, even in the perfect case where all the data is *inside* that folder. The reason is that the "main_includes_path" key in Tool specs is always an absolute path. We support relative paths when *loading* the spec, but when saving it, we always write the absolute path.

I think we can start writing it relative. It can only make things better (as far as I can see) so I will go ahead and do it now.

**Comment by PekkaSavolainen** [comment]
Great. There's another small issue related to Tool spec files #1049. 😉

**Comment by soininen** [comment]
I'm getting this when executing tools:
```
Traceback (most recent call last):
  File "toolbox\spinetoolbox\headless.py", line 121, in _execute
    status = self._open_and_execute_project()
  File "toolbox\spinetoolbox\headless.py", line 168, in _open_and_execute_project
    engine_manager.run_engine(engine_data)
  File "toolbox\spinetoolbox\spine_engine_manager.py", line 139, in run_engine
    self._engine = SpineEngine(**engine_data)
  File "Miniconda3\envs\spinetoolbox\lib\site-packages\spine_engine\spine_engine.py", line 117, in __init__
    self._item_specifications = self._make_item_specifications(specifications, project_item_loader)
  File "Miniconda3\envs\spinetoolbox\lib\site-packages\spine_engine\spine_engine.py", line 144, in _make_item_specifications
    spec = factory.make_specification(spec_dict, self._settings, None)
  File "items\spine_items\tool\specification_factory.py", line 34, in make_specification
    return make_specification(definition, app_settings, logger)
  File "items\spine_items\tool\tool_specifications.py", line 61, in make_specification
    definition_file_path = definition["definition_file_path"]
KeyError: 'definition_file_path'
```

Is this related to the latest changes here?

**Comment by manuelma** [comment]
Probably yes,

But I don't know what's wrong, I added `specification_dict["definition_file_path"] = path` in headless.py :331 to make headless work. Did I miss something? Please fix it if you see it, otherwise I'll do it in about an hour...

**Comment by soininen** [comment]
Never mind. I hadn't update my local branch to latest master. Sorry for the noise!

**Comment by jkiviluo** [comment]
Isn't this done? @manuelma can we close?
