### ISSUE TITLE
Project item renaming broken

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1234]
Project item renaming is broken due to the previous link refactoring. We need to rename the Connections associated with the renamed items as well.

**Comment by manuelma** [comment]
Renaming a project item and then saving breaks the project file. The project fails to load as there's a connection referring to the old name:

```
Traceback (most recent call last):
  File "/home/manuelma/Codes/spine/toolbox/spinetoolbox/widgets/custom_menus.py", line 181, in <lambda>
    lambda checked=False, filepath=filepath: self.call_open_project(checked, filepath),
  File "/home/manuelma/Codes/spine/toolbox/spinetoolbox/widgets/custom_menus.py", line 205, in call_open_project
    if not self._parent.open_project(p):
  File "/home/manuelma/Codes/spine/toolbox/spinetoolbox/ui_main.py", line 460, in open_project
    return self.restore_project(proj_info, load_dir, clear_logs)
  File "/home/manuelma/Codes/spine/toolbox/spinetoolbox/ui_main.py", line 514, in restore_project
    self._project.load(project_items, connections)
  File "/home/manuelma/Codes/spine/toolbox/spinetoolbox/project.py", line 183, in load
    self.add_connection(connection)
  File "/home/manuelma/Codes/spine/toolbox/spinetoolbox/project.py", line 277, in add_connection
    self.dag_handler.add_graph_edge(connection.source, connection.destination)
  File "/home/manuelma/Codes/spine/toolbox/spinetoolbox/dag_handler.py", line 87, in add_graph_edge
    union_dag = nx.union(src_graph, dst_graph)
  File "/home/manuelma/.local/lib/python3.7/site-packages/networkx/algorithms/operators/binary.py", line 54, in union
    if not G.is_multigraph() == H.is_multigraph():
AttributeError: 'NoneType' object has no attribute 'is_multigraph'
```

**Comment by soininen** [comment]
This should be fixed now.

**Comment by manuelma** [comment]
Not sure if it's my fault? When I rename a project item I get this

```
Traceback (most recent call last):
  File "/home/manuelma/Codes/spine/toolbox/spinetoolbox/project_commands.py", line 238, in redo
    if not self._project.rename_item(self._previous_name, self._new_name, box_title):
  File "/home/manuelma/Codes/spine/toolbox/spinetoolbox/project.py", line 306, in rename_item
    if not item.rename(new_name, rename_data_dir_message):
TypeError: rename() takes 2 positional arguments but 3 were given
```

**Comment by soininen** [comment]
Fixed `rename()` signatures in `spine_items`.
