### ISSUE TITLE
File URLs broken in resources

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1241]
When executing a project with Data connection using `--headless-only`, I get this traceback:

```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "Miniconda3\envs\spinetoolbox\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "Miniconda3\envs\spinetoolbox\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "Miniconda3\envs\spinetoolbox\lib\site-packages\spine_engine\spine_engine.py", line 406, in _execute_item_filtered
    output_resources = item.output_resources(ED.FORWARD)
  File "Miniconda3\envs\spinetoolbox\lib\site-packages\spine_engine\project_item\executable_item_base.py", line 123, in output_resources
    }[direction]()
  File "items\spine_items\data_connection\executable_item.py", line 47, in _output_resources_forward
    return scan_for_resources(self, self._files)
  File "items\spine_items\data_connection\output_resources.py", line 32, in scan_for_resources
    return [ProjectItemResource(provider, "file", url=pathlib.Path(ref).as_uri()) for ref in files]
  File "items\spine_items\data_connection\output_resources.py", line 32, in <listcomp>
    return [ProjectItemResource(provider, "file", url=pathlib.Path(ref).as_uri()) for ref in files]
  File "Miniconda3\envs\spinetoolbox\lib\pathlib.py", line 734, in as_uri
    raise ValueError("relative path can't be expressed as a file URI")
ValueError: relative path can't be expressed as a file URI
```

**Comment by soininen** [comment]
Fixed by the above commit.
