### ISSUE TITLE
Selecting gams or executable in Tool Specification Editor produces a traceback

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1252]
When selecting executable in the drop-down menu, this happens.

```
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\spine_items\commands.py", line 97, in redo
    self._callback(self._new_value)
  File "C:\Python38\lib\site-packages\spine_items\tool\widgets\tool_specification_editor_window.py", line 245, in _set_tooltype
    self.ui.textEdit_main_program.set_lexer_name(value)
  File "C:\Python38\lib\site-packages\spine_items\tool\widgets\main_program_text_edit.py", line 72, in set_lexer_name
    self._highlighter.lexer = get_lexer_by_name(lexer_name)
  File "C:\Python38\lib\site-packages\pygments\lexers\__init__.py", line 119, in get_lexer_by_name
    raise ClassNotFound('no lexer for alias %r found' % _alias)
pygments.util.ClassNotFound: no lexer for alias 'executable' found
```

**Comment by manuelma** [comment]
Oh! Sorry about that... Should be easy to fix. We can even try to guess the right lexer from the main program source code if we want....

**Comment by PekkaSavolainen** [comment]
I just catch the ClassNotFound exception from pygments to see if we support the lexer.

**Comment by manuelma** [comment]
Just before we close, no love for the idea of guessing the lexer?

**Comment by PekkaSavolainen** [comment]
Sounds good but I don't know what are the options here because I have not used pygments. Maybe a place for a new issue.
