### ISSUE TITLE
Traceback when checking the Select All check box in Link properties tab when there are no filters to select

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1254]
For example, if there are scenarios but no tools in a database Link properties tab still shows the Select All check box for tools. Trying to check the box gives a Traceback:

```
Traceback (most recent call last):
  File "toolbox\spinetoolbox\project_commands.py", line 335, in redo
    self._resource_filter_model.set_online(self._resource, self._filter_type, self._online)
  File "toolbox\spinetoolbox\mvcmodels\resource_filter_model.py", line 122, in set_online
    self._connection.set_online(resource, filter_type, online)
  File "engine\spine_engine\project_item\connection.py", line 138, in set_online
    current_ids = self._resource_filters[resource][filter_type]
KeyError: 'tool_filter'
```

We probably don't want to show the Select All check box at all if there is nothing to select.

**Comment by soininen** [comment]
Fixed.
