### ISSUE TITLE
The tool execution of SpineOpt seems to lock the result database in parallel execution

### ISSUE THREAD

**Issue by nnhjy** [Spine-project/Spine-Toolbox#1257]
When parallel SpineOpt executions under one tool specification write reports to one database, the database happens to be locked to some of the SpinOpt executions. As a result, the tool specification hangs with the corresponding Julia console of the SpinOpt execution hanging in 'writing reports...'. 

It seems the output database is locked when a SpineOpt execution is writing to it. Other SpineOpt executions being ready to write during this time would be prohibited. Perhaps we should tell the executions to wait and queue until their turn. 

The following error messages were reported in the interpreter window of the toolbox : 
```
Exception happened during processing of request from ('127.0.0.1', 53487)
Traceback (most recent call last):
  File "C:\HJY_tool\Python\Python-3.7.6\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "C:\HJY_tool\Python\Python-3.7.6\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\HJY_tool\Python\Python-3.7.6\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\HJY_tool\Python\Python-3.7.6\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\HJY_projects\spine\data\spinedb_api\spine_db_server.py", line 119, in <lambda>
    (host, port), lambda *args, **kwargs: DBRequestHandler(db_url, upgrade, *args, **kwargs)
  File "C:\HJY_projects\spine\data\spinedb_api\spine_db_server.py", line 43, in __init__
    super().__init__(*args, **kwargs)
  File "C:\HJY_tool\Python\Python-3.7.6\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\HJY_projects\spine\data\spinedb_api\spine_db_server.py", line 101, in handle
    response = handler(*args)
  File "C:\HJY_projects\spine\data\spinedb_api\spine_db_server.py", line 85, in _import_data
    count, errors = import_data(db_map, **data)
  File "C:\HJY_projects\spine\data\spinedb_api\import_functions.py", line 157, in import_data
    updated = update_items(*to_update)
  File "C:\HJY_projects\spine\data\spinedb_api\db_mapping_update_mixin.py", line 88, in _update_object_classes
    return self._update_items("object_class", *items)
  File "C:\HJY_projects\spine\data\spinedb_api\db_mapping_update_mixin.py", line 48, in _update_items
    items, ids = self._items_to_update_and_ids(*items)
  File "C:\HJY_projects\spine\data\spinedb_api\db_mapping_update_mixin.py", line 32, in _items_to_update_and_ids
    item["commit_id"] = self.make_commit_id()
  File "C:\HJY_projects\spine\data\spinedb_api\db_mapping_commit_mixin.py", line 45, in make_commit_id
    self._commit_id = self.connection.execute(ins).inserted_primary_key[0]
  File "C:\HJY_tool\Python\Python-3.7.6\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "C:\HJY_tool\Python\Python-3.7.6\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\HJY_tool\Python\Python-3.7.6\lib\site-packages\sqlalchemy\engine\base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "C:\HJY_tool\Python\Python-3.7.6\lib\site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\HJY_tool\Python\Python-3.7.6\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\HJY_tool\Python\Python-3.7.6\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\HJY_tool\Python\Python-3.7.6\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "C:\HJY_tool\Python\Python-3.7.6\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO "commit" (comment, date, user) VALUES (?, ?, ?)]
[parameters: ('', '2021-03-04 11:11:11.093100', 'anon')]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by manuelma** [comment]
Is there any way we can identify steps from a clean toolbox into this error?

**Comment by nnhjy** [comment]
Hi Manuel! 
A toolbox project to reproduce the error is clean, i.e. there simply needs a SpineOpt tool and an output "datastore". On the other hand, the input "datastore" might have to be somehow large/complex enough to reproduce the crowded "writing report" process. 

Here is one you can try:
[datastore.zip](https://github.com/Spine-project/Spine-Toolbox/files/6101622/datastore.zip)
Run all scenarios together in a toolbox SpineOpt tool with this input datastore. You may probably see the thing. The occurrence of the error doesn't seem guaranteed every time we execute the tool. So you may need another try to see it.

**Comment by nnhjy** [comment]
It seems the problem has been solved somehow for the moment. I will only reopen this issue in case the problem appears again (hope not).

**Comment by manuelma** [comment]
It may be that fixing the parallel imports also fixed this. We had an issue with transactions at a rather low SQLAlchemy level. The Tool uses the same low level mechanism to write changes to the db, so fixing that issue might have helped here as well.

If we have more problems, what basically 'solves' the issue is to provide an example where the issue happens at least half of the times, so we can properly investigate. I think the way to achieve that is going big with the data. @Tasqu was able to manage that for the parallel imports, but I'm afraid there's no exact recipe.
