### ISSUE TITLE
KeyError in exporter spec editor

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1266]
![bug_exporter](https://user-images.githubusercontent.com/11472756/110202521-92734780-7e3f-11eb-9448-898ec0b6d324.png)

```
Traceback (most recent call last):
  File "/home/manuelma/Codes/spine/toolbox/spinetoolbox/helpers.py", line 100, in new_function
    return func(*args, **kwargs)
  File "/home/manuelma/Codes/spine/items/spine_items/exporter/widgets/preview_updater.py", line 334, in _load_data
    write(db_map, writer, self._mapping)
  File "/home/manuelma/Codes/spine/data/spinedb_api/spine_io/exporters/writer.py", line 31, in write
    for title, title_key in titles(root_mapping, db_map):
  File "/home/manuelma/Codes/spine/data/spinedb_api/export_mapping/generator.py", line 81, in titles
    for title, title_key in root_mapping.title(db_map, dict()):
  File "/home/manuelma/Codes/spine/data/spinedb_api/export_mapping/item_export_mapping.py", line 477, in title
    for title_data in self.child.title(db_map, state, fixed_state):
  File "/home/manuelma/Codes/spine/data/spinedb_api/export_mapping/item_export_mapping.py", line 477, in title
    for title_data in self.child.title(db_map, state, fixed_state):
  File "/home/manuelma/Codes/spine/data/spinedb_api/export_mapping/item_export_mapping.py", line 477, in title
    for title_data in self.child.title(db_map, state, fixed_state):
  File "/home/manuelma/Codes/spine/data/spinedb_api/export_mapping/item_export_mapping.py", line 470, in title
    self._update_state(title_state, db_row)
  File "/home/manuelma/Codes/spine/data/spinedb_api/export_mapping/item_export_mapping.py", line 698, in _update_state
    state[Key.OBJECT_LIST_INDEX] += 1
KeyError: <Key.OBJECT_LIST_INDEX: 9>
```

**Comment by manuelma** [comment]
Please checkout my 'fix' above @soininen . Gets around the error but not sure if it's correct. I kinda get the idea of the fixed_state but don't know the origin so well, so I might be missing something.

**Comment by soininen** [comment]
The fix looks OK to me. Thanks for taking care of this! I added a unit test for this particular case into `spinedb_api`.

Currently, some mappings don't support Position.table_name at all so don't be surprised if you run into problems if you try to use time series time stamps as table names. Maybe we need to add `ExportMapping.supports_table_name()` to prevent users breaking the system.

**Comment by manuelma** [comment]
> Maybe we need to add ExportMapping.supports_table_name() to prevent users breaking the system.

I believe this belongs in another issue so I'm closing this now, please reopen if needed.
