### ISSUE TITLE
Toolbox: workflow graph breaks

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1273]
Looks like something is broken in the project item connections. I'm getting this after pulling the latest:

I have two separated workflows in the same project (may or may not be the culprit). I will next remove all connections from project.json.

```
Traceback (most recent call last):
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "spinetoolbox\__main__.py", line 22, in <module>
    return_code = main()
  File "c:\data\spinetoolbox\spinetoolbox\main.py", line 96, in main
    window.init_project(args.project)
  File "c:\data\spinetoolbox\spinetoolbox\ui_main.py", line 332, in init_project
    self.open_project(project_dir, clear_logs=False)
  File "c:\data\spinetoolbox\spinetoolbox\ui_main.py", line 444, in open_project
    return self.restore_project(proj_info, load_dir, clear_logs)
  File "c:\data\spinetoolbox\spinetoolbox\ui_main.py", line 499, in restore_project
    self._project.load(project_items, connections)
  File "c:\data\spinetoolbox\spinetoolbox\project.py", line 185, in load
    self.add_connection(connection)
  File "c:\data\spinetoolbox\spinetoolbox\project.py", line 330, in add_connection
    self.dag_handler.add_graph_edge(connection.source, connection.destination)
  File "c:\data\spinetoolbox\spinetoolbox\dag_handler.py", line 83, in add_graph_edge
    src_graph.add_edge(src_node, dst_node)
AttributeError: 'NoneType' object has no attribute 'add_edge'
```

**Comment by jkiviluo** [comment]
After removing all connections, the project opened.

**Comment by jkiviluo** [comment]
Keeps happening. This time with a bit different traceback (still happens when re-launching Toolbox - was working when I had Toolbox open, although even then the connections disappeared once).

```
Traceback (most recent call last):
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "spinetoolbox\__main__.py", line 22, in <module>
    return_code = main()
  File "c:\data\spinetoolbox\spinetoolbox\main.py", line 96, in main
    window.init_project(args.project)
  File "c:\data\spinetoolbox\spinetoolbox\ui_main.py", line 332, in init_project
    self.open_project(project_dir, clear_logs=False)
  File "c:\data\spinetoolbox\spinetoolbox\ui_main.py", line 444, in open_project
    return self.restore_project(proj_info, load_dir, clear_logs)
  File "c:\data\spinetoolbox\spinetoolbox\ui_main.py", line 499, in restore_project
    self._project.load(project_items, connections)
  File "c:\data\spinetoolbox\spinetoolbox\project.py", line 185, in load
    self.add_connection(connection)
  File "c:\data\spinetoolbox\spinetoolbox\project.py", line 330, in add_connection
    self.dag_handler.add_graph_edge(connection.source, connection.destination)
  File "c:\data\spinetoolbox\spinetoolbox\dag_handler.py", line 87, in add_graph_edge
    union_dag = nx.union(src_graph, dst_graph)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\networkx\algorithms\operators\binary.py", line 54, in union
    if not G.is_multigraph() == H.is_multigraph():
AttributeError: 'NoneType' object has no attribute 'is_multigraph'
```

**Comment by jkiviluo** [comment]
Maybe related to having two separate workflows, since it opens when I connect everything into one workflow.

**Comment by manuelma** [comment]
Can you provide reproducible steps from a clean toolbox project? I've also seen this a couple of times recently, and have got it fixed by butchering project.json file then recreating connections manually...

**Comment by jkiviluo** [comment]
Basically I created two separate workflows in the same workflow

**Comment by jkiviluo** [comment]
Having experienced several subsequent crashes I have to say this does not appear to happen with any pattern I recognize. It can also happen when the DAG is complete.

**Comment by soininen** [comment]
Looking at the `project.json` I think we fail to update the project item connections list properly when items are renamed and deleted.

**Comment by manuelma** [comment]
The commit above fixes the origin of this issue, nice catch!

Unfortunately corrupted projects are not being repaired at the time. I propose we also ignore ghost connections from project.json at loading time. I can give it go.

**Comment by soininen** [comment]
We should ignore ghost and duplicate connections. Both may exist in current projects due to the bug in item deletion.

**Comment by manuelma** [comment]
I'll give a go, so I can get a little bit more familiar with the new Connection object too.
