### ISSUE TITLE
Traceback when opening a project

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1300]
Got this one when trying to open project a when another project was open. Not sure of the exact steps to get this but I think I had the Exporter specification editor open with unsaved changes. Need to investigate more.

```
Traceback (most recent call last):
  File "C:\Users\ttepsa\OneDrive - Teknologian Tutkimuskeskus VTT\Documents\GIT\SPINETOOLBOX\spinetoolbox\widgets\custom_menus.py", line 181, in <lambda>
    lambda checked=False, filepath=filepath: self.call_open_project(checked, filepath),
  File "C:\Users\ttepsa\OneDrive - Teknologian Tutkimuskeskus VTT\Documents\GIT\SPINETOOLBOX\spinetoolbox\widgets\custom_menus.py", line 205, in call_open_project
    if not self._parent.open_project(p):
  File "C:\Users\ttepsa\OneDrive - Teknologian Tutkimuskeskus VTT\Documents\GIT\SPINETOOLBOX\spinetoolbox\ui_main.py", line 456, in open_project
    return self.restore_project(proj_info, load_dir, clear_logs)
  File "C:\Users\ttepsa\OneDrive - Teknologian Tutkimuskeskus VTT\Documents\GIT\SPINETOOLBOX\spinetoolbox\ui_main.py", line 508, in restore_project
    self.populate_specification_model(deserialized_paths)
  File "C:\Users\ttepsa\OneDrive - Teknologian Tutkimuskeskus VTT\Documents\GIT\SPINETOOLBOX\spinetoolbox\ui_main.py", line 723, in populate_specification_model
    spec = self.load_specification_from_file(path)
  File "C:\Users\ttepsa\OneDrive - Teknologian Tutkimuskeskus VTT\Documents\GIT\SPINETOOLBOX\spinetoolbox\ui_main.py", line 758, in load_specification_from_file
    spec = self.load_specification(spec_dict)
  File "C:\Users\ttepsa\OneDrive - Teknologian Tutkimuskeskus VTT\Documents\GIT\SPINETOOLBOX\spinetoolbox\ui_main.py", line 785, in load_specification
    return spec_factory.make_specification(definition, self._qsettings, self)
  File "C:\Python38\lib\site-packages\spine_items\exporter\specification_factory.py", line 34, in make_specification
    return Specification.from_dict(definition)
  File "C:\Python38\lib\site-packages\spine_items\exporter\specification.py", line 171, in from_dict
    mapping_specifications = {
  File "C:\Python38\lib\site-packages\spine_items\exporter\specification.py", line 176, in <dictcomp>
    mapping_from_dict(spec_dict["mapping"]),
  File "C:\Python38\lib\site-packages\spinedb_api\export_mapping\export_mapping.py", line 1315, in from_dict
    flattened.append(mappings[mapping_dict["map_type"]].reconstruct(position, ignorable, mapping_dict))
  File "C:\Python38\lib\site-packages\spinedb_api\export_mapping\export_mapping.py", line 377, in reconstruct
    mapping = cls(position, value=value, header=header, filter_re=filter_re, group_fn=group_fn)
TypeError: __init__() got an unexpected keyword argument 'header'
```

**Comment by PekkaSavolainen** [comment]
Yes, the Exporter spec seems to corrupted now, and opening the project fails every time with the traceback above. Here's the culprit Exporter spec file contents

> {"item_type": "Exporter", "output_format": "csv", "name": "Pekka", "description": "", "mappings": {"Mapping 1": {"type": "object_group_parameter_values", "mapping": [{"map_type": "FixedValue", "position": "table_name", "value": "table"}, {"map_type": "ObjectClass", "position": 0}, {"map_type": "ParameterDefinition", "position": 1}, {"map_type": "ParameterValueList", "position": -1, "ignorable": true}, {"map_type": "Object", "position": 2}, {"map_type": "ObjectGroup", "position": 3}, {"map_type": "Alternative", "position": -5}, {"map_type": "ParameterValue", "position": 5}], "use_fixed_table_name": true}}}

@soininen is there something missing here?

**Comment by soininen** [comment]
Looks like `spinedb_api.export_mapping.item_export_mapping.FixedValueMapping.__init__()` does not have correct signature, i.e. it is missing the required `header` parameter.

**Comment by PekkaSavolainen** [comment]
I think you can reproduce this simply by creating a new Exporter spec, give it some name, and checking the `Fixed table name` checkbox. Click Ok, save, open another project, and open the previous project -> Traceback.

**Comment by manuelma** [comment]
This is probably my fault. Will you fix it @soininen ? otherwise I can do it.

**Comment by soininen** [comment]
@PekkaSavolainen can you check if the problem persists still after pulling `spinedb_api` and `spinetoolbox`?

**Comment by PekkaSavolainen** [comment]
Yes it's fixed now. Thanks a lot.
