### ISSUE TITLE
Importer specification fails (at least for Excel, GDX and csv)

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1301]
After recent changes to the importer, the specification for GDX files does not open properly.

Steps to reproduce:
Make Gdx file Data connection
Make an importer
Connect the gdx file to the importer
Try to open the spec editor for GDX

You should get this:
``` 
Traceback (most recent call last):
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\importer\widgets\import_sources.py", line 190, in update_tables
    t_mapping = ObjectClassMapping()
TypeError: __init__() missing 1 required positional argument: 'position'
```

**Comment by Tasqu** [comment]
For .csv, I get the following traceback:
```
Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "c:\data\spine\spine-engine\spine_engine\utils\returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "c:\data\spine\spine-items\spine_items\importer\do_work.py", line 52, in do_work
    table_mappings, table_options, table_column_convert_specs, table_row_convert_specs, max_rows=-1
  File "c:\data\spine\spine-database-api\spinedb_api\spine_io\importers\reader.py", line 96, in get_mapped_data
    data_source, header = self.get_data_iterator(table, options, max_rows)
  File "c:\data\spine\spine-database-api\spinedb_api\spine_io\importers\csv_reader.py", line 181, in get_data_iterator
    header = first_row
NameError: name 'first_row' is not defined
```

**Comment by jkiviluo** [comment]
For me Excel files work, but csv and xlsx do not. However, Excel doesn't work for Topi either.

**Comment by Tasqu** [comment]
For excel files, the `Import Editor` window doesn't seem to find any data in the file *(nothing in the `Sources` box to be selected)*. Furthermore, when opening the `Import Editor`, I get the following traceback:
```
Traceback (most recent call last):
  File "c:\data\spine\spine-items\spine_items\importer\widgets\import_sources.py", line 190, in update_tables
    t_mapping = ObjectClassMapping()
TypeError: __init__() missing 1 required positional argument: 'position'
```

**Comment by jkiviluo** [comment]
Manuel is working on this now.

**Comment by Tasqu** [comment]
Just for clarity, the previous .csv related traceback was when I tried to run an importer I had configured on an older version. When opening the `Import Editor` for a .csv file, the window doesn't show any data in the file similar to .xlsx files, with the following popping up in the command line:
```
2021-03-17 11:31:02 DEBUG: SHIFT_JIS Japanese prober hit error at byte 53
2021-03-17 11:31:02 DEBUG: EUC-JP Japanese prober hit error at byte 53
2021-03-17 11:31:02 DEBUG: GB2312 Chinese prober hit error at byte 53
2021-03-17 11:31:02 DEBUG: EUC-KR Korean prober hit error at byte 53
2021-03-17 11:31:02 DEBUG: CP949 Korean prober hit error at byte 53
2021-03-17 11:31:02 DEBUG: Big5 Chinese prober hit error at byte 53
2021-03-17 11:31:02 DEBUG: EUC-TW Taiwan prober hit error at byte 53
2021-03-17 11:31:02 DEBUG: windows-1251 Russian confidence = 0.01
2021-03-17 11:31:02 DEBUG: KOI8-R Russian confidence = 0.01
2021-03-17 11:31:02 DEBUG: ISO-8859-5 Russian confidence = 0.01
2021-03-17 11:31:02 DEBUG: MacCyrillic Russian confidence = 0.01
2021-03-17 11:31:02 DEBUG: IBM866 Russian confidence = 0.01
2021-03-17 11:31:02 DEBUG: IBM855 Russian confidence = 0.01
2021-03-17 11:31:02 DEBUG: ISO-8859-7 Greek confidence = 0.01
2021-03-17 11:31:02 DEBUG: windows-1253 Greek confidence = 0.01
2021-03-17 11:31:02 DEBUG: ISO-8859-5 Bulgairan confidence = 0.01
2021-03-17 11:31:02 DEBUG: windows-1251 Bulgarian confidence = 0.01
2021-03-17 11:31:02 DEBUG: TIS-620 Thai confidence = 0.01
2021-03-17 11:31:02 DEBUG: ISO-8859-9 Turkish confidence = 0.6267752271548169
2021-03-17 11:31:02 DEBUG: windows-1255 Hebrew confidence = 0.0
2021-03-17 11:31:02 DEBUG: windows-1255 Hebrew confidence = 0.0
2021-03-17 11:31:02 DEBUG: windows-1255 Hebrew confidence = 0.0
Traceback (most recent call last):
  File "c:\data\spine\spine-items\spine_items\importer\widgets\import_sources.py", line 190, in update_tables
    t_mapping = ObjectClassMapping()
TypeError: __init__() missing 1 required positional argument: 'position'
```

**Comment by manuelma** [comment]
Thanks, should be done in about an hour.

**Comment by manuelma** [comment]
Sorry for the inconvenience. Should work better now. Please pull toolbox master and let me know if you run into any more trouble.

**Comment by Tasqu** [comment]
@manuelma .xlsx import editing and importing seems to work now. However, I can't access the `data` in the `Sources` box of .csv importer. I get a popup with an error
```
Could not get data from source: name 'first_row' is not defined
```
but no traceback in the command line.

**Comment by Tasqu** [comment]
If I try to run a pre-configured .csv importer, toolbox starts executing it but gets stuck with the following traceback
```
Process ReturningProcess-2:
Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "c:\data\spine\spine-engine\spine_engine\utils\returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "c:\data\spine\spine-items\spine_items\importer\do_work.py", line 52, in do_work
    table_mappings, table_options, table_column_convert_specs, table_row_convert_specs, max_rows=-1
  File "c:\data\spine\spine-database-api\spinedb_api\spine_io\importers\reader.py", line 96, in get_mapped_data
    data_source, header = self.get_data_iterator(table, options, max_rows)
  File "c:\data\spine\spine-database-api\spinedb_api\spine_io\importers\csv_reader.py", line 181, in get_data_iterator
    header = first_row
NameError: name 'first_row' is not defined
```

**Comment by manuelma** [comment]
Can you try pulling toolbox master again?

**Comment by manuelma** [comment]
It should ask you to upgrade spinedb_api at startup

**Comment by Tasqu** [comment]
Ok, the .csv gets displayed now in the importer at least

**Comment by Tasqu** [comment]
Seems to accept specifications and import as intended

**Comment by Tasqu** [comment]
Seems to work for my pre-configured .csv as well.

**Comment by jkiviluo** [comment]
I had a problem that it did not show new Excel sheets, but that also is fixed.

**Comment by manuelma** [comment]
Ok, thanks. Please let me know if you run into more issues (also talk to me on slack if urgent).

To explain, we have completely refactored the importer backend recently. Turns out we learned a lot by implementing the *exporter* backend, about how to make things more scalable and maintainable. We didn't have that insight when developing the importer and that led us to patch things ad hoc, and in the end we had quite a Frankenstein monster.

But now it's better, and with your help I think we can tie the remaining ends (hopefully not too many at this point).

**Comment by Tasqu** [comment]
Ah, one of my old .csv imports still seems to get stuck when executed with the following traceback:
```
Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "c:\data\spine\spine-engine\spine_engine\utils\returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "c:\data\spine\spine-items\spine_items\importer\do_work.py", line 52, in do_work
    table_mappings, table_options, table_column_convert_specs, table_row_convert_specs, max_rows=-1
  File "c:\data\spine\spine-database-api\spinedb_api\spine_io\importers\reader.py", line 103, in get_mapped_data
    data_source, mappings, header, table, column_convert_fns, row_convert_fns
  File "c:\data\spine\spine-database-api\spinedb_api\import_mapping\generator.py", line 110, in get_mapped_data
    full_row.append(row[last_non_pivoted_column_pos + k])
IndexError: list index out of range
```
When opening the `Import Editor`, I get the following popup:
```
Could not get tables from source: UTF-16 stream does not start with BOM
```
And when viewing the data in the `Import Editor` by selecting the `Source`, I get the following traceback:
```
Traceback (most recent call last):
  File "c:\data\spine\spine-items\spine_items\importer\widgets\import_sources.py", line 240, in update_preview_data
    for row, row_type in row_types.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by manuelma** [comment]
can you share the importer spec and the source data?

**Comment by Tasqu** [comment]
Here's the importer specification *(which I had to convert to .txt for GitHub to upload it)*
[structure_layers_importer.txt](https://github.com/Spine-project/Spine-Toolbox/files/6155538/structure_layers_importer.txt)

Unfortunately, I cannot share the data it's supposed to import as it's confidential 😞

**Comment by Tasqu** [comment]
It's a weird issue in any case. I have two .csv files that are read using the same importer specification, but only one of them seems to have this issue.

**Comment by manuelma** [comment]
Maybe you can tell me how many rows and columns those csvs have and I can make dummy versions of them to try...

**Comment by Tasqu** [comment]
I'm working on a dummy .csv now, let's see if it throws the same errors.

**Comment by Tasqu** [comment]
@manuelma 1373 rows (header included) and 11 columns. I tried removing the majority of the rows from the original .csv to see if I still got the error, but didn't seem like it.

**Comment by Tasqu** [comment]
I also have a 72K row .csv that I'm trying to import, but I haven't got to that yet due to the original issue 😄

**Comment by manuelma** [comment]
I see the issue, will fix it now. Thanks!

**Comment by Tasqu** [comment]
Oh, looks like the `Ignore columns` option is broken in the importer. I wonder if that could be causing this, or if it's unrelated.

**Comment by manuelma** [comment]
@Tasqu can you please pull latest spinedb_api and see if that helps with your mapping problem?

Do you use ignore columns for this mapping?

**Comment by Tasqu** [comment]
@manuelma I'll try. I do use it *(or did)*, but it seems that opening `Import Editor` for a specification with `ignore columns` and changing anything gets rid of it when the specs are updated.

**Comment by manuelma** [comment]
You should have a json.bak file next to the new specification file that has the old format, can you share that as well to investigate the ignore columns issue?

**Comment by manuelma** [comment]
Also, how is ignore columns supposed to work in your opinion?

**Comment by Tasqu** [comment]
Didn't seem to solve my issue. When opening the import editor i still get the popup
```
Could not get tables from source: UTF-16 stream does not start with BOM
```
When opening the `data` in the `Sources` view of the import editor I get the traceback
```
(spinetoolbox) C:\data\Desktop>CALL python -m spinetoolbox
Traceback (most recent call last):
  File "c:\data\spine\spine-items\spine_items\importer\widgets\import_sources.py", line 240, in update_preview_data
    for row, row_type in row_types.items():
AttributeError: 'NoneType' object has no attribute 'items'
```
And when running the importer toolbox gets stuck with a traceback:
```
Process ReturningProcess-1:
Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "c:\data\spine\spine-engine\spine_engine\utils\returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "c:\data\spine\spine-items\spine_items\importer\do_work.py", line 52, in do_work
    table_mappings, table_options, table_column_convert_specs, table_row_convert_specs, max_rows=-1
  File "c:\data\spine\spine-database-api\spinedb_api\spine_io\importers\reader.py", line 110, in get_mapped_data
    errors.extend([(table, f"Could not map row: {row_number}, Error: {err}") for row_number, err in t_errors])
  File "c:\data\spine\spine-database-api\spinedb_api\spine_io\importers\reader.py", line 110, in <listcomp>
    errors.extend([(table, f"Could not map row: {row_number}, Error: {err}") for row_number, err in t_errors])
ValueError: too many values to unpack (expected 2)
```

**Comment by manuelma** [comment]
I'm afraid you're going to need to share some of that data. Just a couple of rows, and change the numbers...?

**Comment by Tasqu** [comment]
Here's the .bak file *(again in .txt due to github)*. 
[structure_layers.json - Copy.txt](https://github.com/Spine-project/Spine-Toolbox/files/6156019/structure_layers.json.-.Copy.txt)
The `skip_columns` field is missing from the .json file

**Comment by soininen** [comment]
@manuelma your latest commit to `spinedb_api` did not update version number. Was it intended?

**Comment by Tasqu** [comment]
@manuelma Well, the weird thing is that I don't run into any importer issues if I mess with the data itself. I've tried removing data entries so that I've only got a row or so, and I get no issues. Now I tried replacing all actual data in the .csv with dummy data, and it imports without issues.

I would suspect it's something with the data itseld, butI haven't messed with the data itself since 23rd of February, and I'm fairly certain things worked back then.

**Comment by manuelma** [comment]
> @manuelma your latest commit to spinedb_api did not update version number. Was it intended?

**Comment by manuelma** [comment]
> Now I tried replacing all actual data in the .csv with dummy data, and it imports without issues.

Can you share that data? Anything that causes the issue so I can investigate more efficiently, please.

**Comment by Tasqu** [comment]
>Can you share that data? Anything that causes the issue so I can investigate more efficiently, please.

That's the thing, it doesn't cause any issues. The dummy data imports just fine.

**Comment by manuelma** [comment]
Oh, sorry, I misread.... Can you share the data through Teams or some other secure mechanism?

**Comment by manuelma** [comment]
Also you may try again with latest spinedb_api, might help figure out the error...

**Comment by Tasqu** [comment]
I'll have to see if I can find a way to replicate the issue with something I can share.

**Comment by manuelma** [comment]
You can also try pulling latest toolbox master. I 'guessed' some fixes based on the tracebacks you posted, maybe it helps.

**Comment by Tasqu** [comment]
@manuelma Ok, I might have an idea why my import isn't working. I've got a column of type `Float` with rows that have no values in that column. It used to work with the old importer, but I'm guessing something has changed so that this causes problems now.

**Comment by manuelma** [comment]
Thanks @Tasqu 

Is this with latest toolbox master?

**Comment by Tasqu** [comment]
>Is this with latest toolbox master?

I believe it was, but I'll have to check this further tomorrow.

**Comment by Tasqu** [comment]
@manuelma Yeah, it seems that with the latest `masters`, the importer no longer gets stuck but exits on errors. As far as I can tell from the importer error log, the reason indeed seems to be the empty rows in a column typed `float`.

I suppose the question is, do we want to restore this to work as it did previously, where the importer simply skipped any such entries? In the data processing flow I'm running into this error, I have actually been relying on the old behaviour. However, changing the empty values to something like -1 would work in my case as well, but can the same be said for other use-cases?

**Comment by manuelma** [comment]
Hi @Tasqu 

Thanks for testing. I think we should restore the old functionality.

I am looking at the old code, and what it did was to convert empty strings to None, regardless of the specified type. Would that work out for you?

**Comment by Tasqu** [comment]
@manuelma It probably would, but I can't know for sure unless I test it 😄 

I'll still have to check whether the `ignore columns` option in the importer works as intended. So far, I've been able to circumvent it by using my old importer specs, as tampering with them seems to always reset the ignored columns.

**Comment by manuelma** [comment]
You're right, we need to fix ignore columns too. I will try and fix it now.

**Comment by jkiviluo** [comment]
Is this done? Should @Tasqu test?

**Comment by manuelma** [comment]
Seems to work.

**Comment by Tasqu** [comment]
@jkiviluo As far as I'm concerned, this issue has been resolved. I opened a new one #1318 for further issues, but my old importers work as intended again.
