### ISSUE TITLE
Importer: Importer trying to import data even when no data defined

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1325]
This is bit complicated to explain. Hence, attached is a small project. If you execute the importer, the importer log has error messages that maybe indicate that the two of three mappings in the gridNode are trying to import data even though they are just group membersip mappings.

[FlexTool2.zip](https://github.com/Spine-project/Spine-Toolbox/files/6196266/FlexTool2.zip)

**Comment by manuelma** [comment]
I get a different error when running that importer...

```
Traceback (most recent call last):
  File "/home/manuelma/miniconda3/envs/spinetoolbox/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/manuelma/Codes/spine/engine/spine_engine/utils/returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "/home/manuelma/Codes/spine/items/spine_items/importer/do_work.py", line 56, in do_work
    table_mappings, table_options, table_column_convert_specs, table_row_convert_specs, max_rows=-1
  File "/home/manuelma/Codes/spine/data/spinedb_api/spine_io/importers/reader.py", line 103, in get_mapped_data
    data_source, mappings, header, table, column_convert_fns, row_convert_fns
  File "/home/manuelma/Codes/spine/data/spinedb_api/import_mapping/generator.py", line 78, in get_mapped_data
    row = _convert_row(row, column_convert_fns, start_pos + k, errors)
  File "/home/manuelma/Codes/spine/data/spinedb_api/import_mapping/generator.py", line 125, in _convert_row
    item = convert_fn(item)
  File "/home/manuelma/Codes/spine/data/spinedb_api/import_mapping/type_conversion.py", line 50, in __call__
    return constructor(value)
TypeError: float() argument must be a string or a number, not 'NoneType'
```

I'm fixing this now and will bump the version, I suspect you're not on latests masters @jkiviluo ... we probably forgot to force an update...

**Comment by manuelma** [comment]
Done. Please, can you pull latest master and confirm there's still an issue? (whenever you get the chance)

**Comment by jkiviluo** [comment]
Good work! 

There are still these errors (as you said, they are caused by empty cells - those can be valid entries for data and should be interpreted as no data). I think the best way to deal with these is to sum how many there were and report it in one line per sheet.

`('units', "Could not convert 'None' to type 'float' (near row 1)")`

Then I also get these below from the gridNode sheet. I think they are caused by multiple mappings and that the importer tries to pick them up although it's parsing through the object group mappings and these cells are not mapped in those mappings.

`('gridNode', "Could not convert 'capacity margin (MW)' to type 'float' (near row 0)")`

**Comment by manuelma** [comment]
I think the problem is the importer now converts data to the right type as a very first step, before even looking at what columns/rows are actually in the mapping. So I think the solution is to invert those steps... Will do it soon.

**Comment by jkiviluo** [comment]
Now the importer gets stuck on ts_energy of DemoModel-1.xlsx.

```
C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\openpyxl\worksheet\_reader.py:300: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
Process ReturningProcess-5:
Traceback (most recent call last):
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_engine\utils\returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\importer\do_work.py", line 56, in do_work
    table_mappings, table_options, table_column_convert_specs, table_row_convert_specs, max_rows=-1
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spinedb_api\spine_io\importers\reader.py", line 103, in get_mapped_data
    data_source, mappings, header, table, column_convert_fns, row_convert_fns
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 114, in get_mapped_data
    _make_parameter_values(mapped_data)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 215, in _make_parameter_values
    row[value_pos] = _parameter_value_from_dict(value)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 225, in _parameter_value_from_dict
    return _table_to_map(d["data"], compress=d.get("compress", False))
KeyError: 'data'
```

**Comment by manuelma** [comment]
Has the project changed? I get a different traceback here...

**Comment by jkiviluo** [comment]
Maybe all the importer settings were not correct. Alternative should be changed to 'Base'. I can wrap the project again.

**Comment by manuelma** [comment]
nevermind, I see it now.

I will fix it right away.

I think the problem is in handling those empty cells to the right of the data. It's not 100% clear to me what to do with those, and it looks like the desired behavior is to 'skip' them somehow?

**Comment by jkiviluo** [comment]
Yes, we should skip them. The detection when to end should start after all columns that have been assigned for the different dimensions (e.g. object 1). For columns, it would go rightward (sorry part of the world) and stop when there is no more data - or maybe no more object names or whatever is on the first row(s). For rows, the same, but downward. To be fancy, we could allow a setting where the user can define how many empty columns/rows is ok to skip.

**Comment by jkiviluo** [comment]
If you now use the button 'read until empty column on first row' on those example tables, it doesn't work, because the A1 cellcolumn is empty.

**Comment by manuelma** [comment]
Ok I think I understand. Will try to do something.

**Comment by manuelma** [comment]
I think one probably bigger issue here, is that this seems to never end. Data comes in so many different forms, and it looks like we're constantly refactoring this to handle some specific conditions? Don't you have that feeling?

**Comment by jkiviluo** [comment]
To be really fancy, you could also put -1 in order to ignore the last column, etc.

**Comment by jkiviluo** [comment]
> Data comes in so many different forms, and it looks like we're constantly refactoring this to handle some specific conditions? Don't you have that feeling?

As long as we are addressing each issue in a generic manner, I think we are improving and covering a larger percentage of possible situations. I think this is really important piece in order to make Toolbox the modelling platform of choice.

**Comment by manuelma** [comment]
I agree. I think at some point we need a sort of stop gap: tell the user to review their mapping and give them some hints, like ignore empty columns, something like that. At the moment the error messages are really cryptic, not communicated to the user. It actually just hangs...

**Comment by jkiviluo** [comment]
Bugs we need to fix anyway. And yes, we cannot serve every possible situation. But it can also be very demanding to convert your format. That format may be used by hundreds of users for various purposes. If Toolbox offers the functionality, it's much easier to convert data (and people).

**Comment by manuelma** [comment]
It might work better in latest master.

**Comment by jkiviluo** [comment]
Looks great. It seems to import everything, but I still get these warnings from the 'units' table:

```
Could not import relationship with objects ('Wind', 'wind', 'elec', 'nodeA') into 'unitGroup__unit__grid__node__fuel': Some of the objects in relationship 'unitGroup__unit__grid__node__fuel_Wind__wind__elec__nodeA' are invalid.
```

As far as I can see, it's imported correctly despite that warning.

**Comment by manuelma** [comment]
Nice, I can look into that next.

I'm also thinking it would be good to automate all the tests your running. We could use @soininen headless testing approach with this project, all the tables checked... Would that work?

I think @Tasqu also has some interesting cases in form of projects. We could do the same with those (if any) by altering the confidential data?

**Comment by jkiviluo** [comment]
Absolutely would make sense to have tests for imports and exports.

I think the data should be done really small and simple - this is too big, I was too lazy to strip it down. Maybe we can discuss in next Toolbox meeting who could be tasked with the tests.

**Comment by manuelma** [comment]
Any issues left here?

**Comment by jkiviluo** [comment]
I still get those 'errors' from the empty cells. The current message is like this:

```
[30-03-2021 16:34:39] ***Executing Importer ImportOrig***
[30-03-2021 16:34:43] Importing template.xlsm
[30-03-2021 16:35:14] Successfully read 922327 data.
[30-03-2021 16:35:18] Errors while importing a table.
[30-03-2021 16:35:18] Ignoring errors. Set Cancel import on error to bail out instead.
[30-03-2021 16:35:18] Inserted 629 data with 91 errors into sqlite:///C:\data\Toolbox_projects\FlexTool3\FlexTool2D_data.sqlite?spinedbfilter=cfg%3Aexecution%3A%7B%22execution_item%22%3A+%22ImportOrig%22%2C+%22scenarios%22%3A+%5B%5D%2C+%22timestamp%22%3A+%222021-03-30T16%3A34%3A39%22%7D
[30-03-2021 16:35:18] Error log
[30-03-2021 16:35:18] Executing Importer ImportOrig finished
```

It should rather be something like this:


[30-03-2021 16:34:39] ***Executing Importer ImportOrig***
[30-03-2021 16:34:43] Importing template.xlsm
[30-03-2021 16:35:14] Successfully read 922327 data.
~~[30-03-2021 16:35:18] Errors while importing a table.~~
~~[30-03-2021 16:35:18] Ignoring errors. Set Cancel import on error to bail out instead.~~
[30-03-2021 16:35:18] Inserted 629 data into sqlite:///C:\data\Toolbox_projects\FlexTool3 \FlexTool2D_data.sqlite?spinedbfilter=cfg%3Aexecution%3A%7B%22execution_item%22%3A+%22ImportOrig%22%2C+%22scenarios%22%3A+%5B%5D%2C+%22timestamp%22%3A+%222021-03-30T16%3A34%3A39%22%7D
**[30-03-2021 16:35:18] Skipped 91 empty cells**
~~[30-03-2021 16:35:18] Error log~~
[30-03-2021 16:35:18] Executing Importer ImportOrig finished
`

**Comment by manuelma** [comment]
ok, thanks. Can you confirm that those errors are from empty cells now? I though I wasn't logging those anymore... What does the log message say exactly?

**Comment by jkiviluo** [comment]
It says this:

```
Could not import relationship with objects ('elec', 'nodeC') into 'grid__node__nodeGroup': Some of the objects in relationship 'grid__node__nodeGroup_elec__nodeC' are invalid.
Could not import relationship with objects ('csp', 'B_CSP') into 'grid__node__nodeGroup': Some of the objects in relationship 'grid__node__nodeGroup_csp__B_CSP' are invalid.
Could not import relationship with objects ('heat', 'heatA') into 'grid__node__nodeGroup': Some of the objects in relationship 'grid__node__nodeGroup_heat__heatA' are invalid.

etc.
```

But these are due to empty 'relationships' that shouldn't be reported as errors - it's just that the tabular format creates situations where you don't actually have a relationship entity for every combination.

![image](https://user-images.githubusercontent.com/40472544/113016606-53f35300-9187-11eb-9082-ab37e2cd52df.png)

**Comment by jkiviluo** [comment]
So, I think you're covering empty parameter values, but this is different.

**Comment by manuelma** [comment]
I'm not sure how is that different? I'm thinking how to tell that situation apart from an actual mistake, where an object name has to be there but it's not, and I want toolbox to tell me so. In this case the user is mapping that column to an object name and the object is missing. If for any reason they don't care about this, they can check cancel on error and then ignore those log messages. But I'm pretty sure there will be a user that wants to see that message. What am I missing?

**Comment by jkiviluo** [comment]
I get 91 one of them and the situation is not 'invalid' - I start ignoring the error messages and I would then miss real errors. 

You're of course right that sometimes this situation is a real problem and I guess we have no way to tell them apart. Only option would be to have a check box for each mapped object class whether to fail on empty values. It's kind of related to the 'import objects' that I at some point suggested to be moved to an object class level decision (https://github.com/Spine-project/Spine-Toolbox/issues/1015).

**Comment by manuelma** [comment]
yeah, it's not easy. I think it has to be a setting, unless we want to be bold: just don't consider them as errors and see if we run into trouble?

**Comment by jkiviluo** [comment]
I guess I feel that your point about missing real errors is more important than the convenience of not seeing error messages at all. If we cannot implement the best solution (allow object class specific treatment) right now, then it's better to err on the side of caution. My previous comment keeps that caution, but would make it bit nicer for the user that has my issue.

**Comment by manuelma** [comment]
I believe a good solution would be something like "don't show this error again"> We can open the error log in a mini interface where the user can whitelist specific errors, and those get save somehow in the importer spec. The next time the importer runs and finds errors, it would then check if the errors aren't whitelisted and silence them otherwise... I think that's manageable?

**Comment by jkiviluo** [comment]
We could have these options for each 'object dimension':

( ) 'import objects if object does not exist'
( ) 'require objects to exist (import fails if object missing)'

( ) 'log errors for missing objects'
( ) 'do not include missing objects in the log'

These are two separate radio buttons, but if you choose 'import objects if object does not exist' then presumably you shouldn't need to use the 2nd radio button choice.

I guess that 'don't show this error again' would check the 'do not include missing objects in the log' (but for which object dimension?). I'm just thinking that we shouldn't implement something that would not be compatible with the final solution.

**Comment by jkiviluo** [comment]
...and I guess these should be for 'entities'. You can also either have the relationship or then not have it.
