### ISSUE TITLE
Importer: fails on a particular table

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1326]
I'm trying to import time series data (ts_cf). One file works (template.xlsx), but another doesn't (demoModel-1.xlsx). Not sure where the problem is. The project attached.

```
Traceback (most recent call last):
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_engine\utils\returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\importer\do_work.py", line 56, in do_work
    table_mappings, table_options, table_column_convert_specs, table_row_convert_specs, max_rows=-1
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spinedb_api\spine_io\importers\reader.py", line 103, in get_mapped_data
    data_source, mappings, header, table, column_convert_fns, row_convert_fns
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 114, in get_mapped_data
    _make_parameter_values(mapped_data)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 215, in _make_parameter_values
    row[value_pos] = _parameter_value_from_dict(value)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 225, in _parameter_value_from_dict
    return _table_to_map(d["data"], compress=d.get("compress", False))
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 238, in _table_to_map
    d = _table_to_dict(table)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 254, in _table_to_dict
    d[row[-2]] = row[-1]
TypeError: 'float' object does not support item assignment
```

[FlexTool2.zip](https://github.com/Spine-project/Spine-Toolbox/files/6197834/FlexTool2.zip)

**Comment by manuelma** [comment]
Thanks! I see it and will fix it now.

**Comment by manuelma** [comment]
Seems to work now, can you pull latest spinedb_api and try? I haven't bumped the version.

The issue seems to be that last column with only empty values that is confusing the importer.

**Comment by jkiviluo** [comment]
Yes, it works now. Thanks!
