### ISSUE TITLE
Traceback in DB Editor

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1330]
1. Make Data store and empty database
2. Open Database editor
3. Add an object class
4. Rollback

I get this Traceback:

```
Traceback (most recent call last):
  File "oolbox\spinetoolbox\mvcmodels\minimal_tree_model.py", line 288, in data
    return item.data(index.column(), role)
  File "toolbox\spinetoolbox\spine_db_editor\mvcmodels\entity_tree_item.py", line 114, in data
    return super().data(column, role)
  File "toolbox\spinetoolbox\spine_db_editor\mvcmodels\multi_db_tree_item.py", line 374, in data
    return self.display_icon
  File "toolbox\spinetoolbox\spine_db_editor\mvcmodels\entity_tree_item.py", line 96, in display_icon
    return self._display_icon()
  File "toolbox\spinetoolbox\spine_db_editor\mvcmodels\entity_tree_item.py", line 100, in _display_icon
    self.first_db_map, self.item_type, self.db_map_id(self.first_db_map), for_group=for_group
  File "toolbox\spinetoolbox\spine_db_manager.py", line 610, in entity_class_icon
    self.entity_class_renderer(db_map, entity_type, entity_class_id, for_group=for_group)
  File "toolbox\spinetoolbox\spine_db_icon_manager.py", line 171, in icon_from_renderer
    return QIcon(SceneIconEngine(renderer.scene))
AttributeError: 'NoneType' object has no attribute 'scene'
```

**Comment by soininen** [comment]
Resolved.
