### ISSUE TITLE
Using python3 kernel provided by miniconda in Python Console does not work

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1333]
Installing miniconda installs a kernel called `python3` into user's system Python. It is found e.g. in `C:\Python38\share\jupyter\kernels\python3`. If Spine Toolbox is launched using C:\Python38\python.exe, this `python3` can be selected as the kernel for Python Consoles in Settings->Tools. However, if user selects this kernel and executes a Python Tool, executions fails with the following traceback **(ON WINDOWS)**:

```
Exception in thread Thread-31:
Traceback (most recent call last):
  File "C:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python38\lib\site-packages\spine_engine\spine_engine.py", line 400, in _execute_item_filtered
    item_success = item.execute(filtered_forward_resources, filtered_backward_resources)
  File "C:\Python38\lib\site-packages\spine_items\tool\executable_item.py", line 403, in execute
    self._tool_instance.prepare(expanded_args)
  File "C:\Python38\lib\site-packages\spine_items\tool\tool_instance.py", line 199, in prepare
    self.exec_mngr = KernelExecutionManager(
  File "C:\Python38\lib\site-packages\spine_engine\execution_managers.py", line 218, in __init__
    self._kernel_manager = _kernel_manager_factory.new_kernel_manager(
  File "C:\Python38\lib\site-packages\spine_engine\execution_managers.py", line 144, in new_kernel_manager
    km.start_kernel(stdout=blackhole, stderr=blackhole, **kwargs)
  File "C:\Python38\lib\site-packages\jupyter_client\manager.py", line 337, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "C:\Python38\lib\site-packages\jupyter_client\manager.py", line 286, in pre_start_kernel
    self.write_connection_file()
  File "C:\Python38\lib\site-packages\jupyter_client\connect.py", line 466, in write_connection_file
    self.connection_file, cfg = write_connection_file(self.connection_file,
  File "C:\Python38\lib\site-packages\jupyter_client\connect.py", line 136, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Python38\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\Python38\lib\site-packages\jupyter_core\paths.py", line 461, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Python38\lib\site-packages\jupyter_core\paths.py", line 387, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed while importing win32api: The specified module could not be found.
```

The workaround here is to **create a new kernel using the Settings->Tools->Kernel Editor and not use the `python3` kernel**.

**Comment by PekkaSavolainen** [comment]
This actually happens on other kernels too. The problem here is system Python 3.8 and pywin32=225,

Closed as duplicate of #1230. See #1230 for updates.
