### ISSUE TITLE
Execution test failure: socket address already in use

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1336]
I have seen this Traceback a few times during GitHub action runs:

```
2021-03-26 07:48:15 INFO: ***Executing Data Store <b>Data store</b>***
2021-03-26 07:48:15 INFO: Executing Data Store Data store finished
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/spine_engine/spine_engine.py", line 400, in _execute_item_filtered
    item_success = item.execute(filtered_forward_resources, filtered_backward_resources)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/spine_items/tool/executable_item.py", line 400, in execute
    with labelled_resource_args(forward_resources + backward_resources, use_db_server) as labelled_args:
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/spine_items/utils.py", line 108, in labelled_resource_args
    server_url = result[resource.label] = start_spine_db_server(resource.url)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/site-packages/spinedb_api/spine_db_server.py", line 119, in start_spine_db_server
    (host, port), lambda *args, **kwargs: DBRequestHandler(db_url, upgrade, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/opt/hostedtoolcache/Python/3.7.10/x64/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

**Comment by soininen** [comment]
Cannot reproduce this even after a dozen retries. Hopefully this was something that happens only once in a lifetime.

**Comment by soininen** [comment]
Just when I managed to close this issue the test failed on Ubuntu with Python 3.8.

**Comment by soininen** [comment]
Haven't seen this issue for a long time now.
