### ISSUE TITLE
Importer: Parallel imports with lots of data hit sqlite timeout

### ISSUE THREAD

**Issue by Tasqu** [Spine-project/Spine-Toolbox#1347]
There are two issues that I keep running into when trying to import data from multiple sources in parallel. Here's a dummy project to replicate the issues, at least partially:

[parallel_importer_issues.zip](https://github.com/Spine-project/Spine-Toolbox/files/6229003/parallel_importer_issues.zip)

For reference, my actual use-case looks like this:

![image](https://user-images.githubusercontent.com/77660814/112989750-eb4bac80-916d-11eb-837e-87600d6e5497.png)

Unfortunately, due to the confidentiality of the data, I cannot share the actual project.

## Issue 1

Sometimes the importers fail due to errors while importing that don't happen when running the importer by itself. The error log sometimes also logs errors about missing `object_classes` that don't occur while running the importer by itself.

Unfortunately, my dummy project doesn't seem to get similar error logs to my actual use case on this front, but produce another error while failing the imports. My actual importers occasionally produce error logs like:
```
Could not import parameter 'year' with class 'source': Missing entity class id for parameter definition 'year'.
...
Could not import parameter 'description' with class 'source': Missing entity class id for parameter definition 'description'.
...
Could not import object 'ETOL_1800' with class 'source': Object class id for object 'ETOL_1800' not found.
...
Could not import parameter value for 'ETOL_1800', class 'source', parameter 'year': Parameter not found.
...
```
even though the importer runs solo just fine.

## Issue 2

Sometimes, the importers end up in limbo, appearing as if they are still processing in toolbox while producing the following monster of a traceback:

```
Process ReturningProcess-4:
Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "c:\data\spine\spine-engine\spine_engine\utils\returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "c:\data\spine\spine-items\spine_items\importer\do_work.py", line 89, in do_work
    success = _import_data_to_url(cancel_on_error, logs_dir, all_data, url, logger)
  File "c:\data\spine\spine-items\spine_items\importer\do_work.py", line 104, in _import_data_to_url
    import_num, import_errors = spinedb_api.import_data(db_map, **data)
  File "c:\data\spine\spine-database-api\spinedb_api\import_functions.py", line 162, in import_data
    added = add_items(*to_add)
  File "c:\data\spine\spine-database-api\spinedb_api\db_mapping_add_mixin.py", line 319, in _add_object_classes
    return self._add_items("object_class", *items)
  File "c:\data\spine\spine-database-api\spinedb_api\db_mapping_add_mixin.py", line 147, in _add_items
    items_to_add, ids = self._items_and_ids(tablename, *items)
  File "c:\data\spine\spine-database-api\spinedb_api\db_mapping_add_mixin.py", line 105, in _items_and_ids
    self.connection.execute(stmt, {"user": self.username, "date": datetime.utcnow(), fieldname: new_next_id})
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute    return meth(self, multiparams, params)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: UPDATE next_id SET user=?, date=?, entity_class_id=?]
[parameters: ('Importer', datetime.datetime(2021, 3, 30, 12, 27, 52, 706299), 11)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Process ReturningProcess-8:
Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "c:\data\spine\spine-engine\spine_engine\utils\returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "c:\data\spine\spine-items\spine_items\importer\do_work.py", line 89, in do_work
    success = _import_data_to_url(cancel_on_error, logs_dir, all_data, url, logger)
  File "c:\data\spine\spine-items\spine_items\importer\do_work.py", line 104, in _import_data_to_url
    import_num, import_errors = spinedb_api.import_data(db_map, **data)
  File "c:\data\spine\spine-database-api\spinedb_api\import_functions.py", line 162, in import_data
    added = add_items(*to_add)
  File "c:\data\spine\spine-database-api\spinedb_api\db_mapping_add_mixin.py", line 319, in _add_object_classes
    return self._add_items("object_class", *items)
  File "c:\data\spine\spine-database-api\spinedb_api\db_mapping_add_mixin.py", line 147, in _add_items
    items_to_add, ids = self._items_and_ids(tablename, *items)
  File "c:\data\spine\spine-database-api\spinedb_api\db_mapping_add_mixin.py", line 105, in _items_and_ids
    self.connection.execute(stmt, {"user": self.username, "date": datetime.utcnow(), fieldname: new_next_id})
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute    return meth(self, multiparams, params)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: UPDATE next_id SET user=?, date=?, entity_class_id=?]
[parameters: ('Importer', datetime.datetime(2021, 3, 30, 12, 27, 52, 796666), 11)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\pool\base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\pool\base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\default.py", line 543, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: Cannot operate on a closed database.
Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\pool\base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\pool\base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\default.py", line 543, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: Cannot operate on a closed database.
Process ReturningProcess-9:
Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "c:\data\spine\spine-engine\spine_engine\utils\returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "c:\data\spine\spine-items\spine_items\importer\do_work.py", line 89, in do_work
    success = _import_data_to_url(cancel_on_error, logs_dir, all_data, url, logger)
  File "c:\data\spine\spine-items\spine_items\importer\do_work.py", line 104, in _import_data_to_url
    import_num, import_errors = spinedb_api.import_data(db_map, **data)
  File "c:\data\spine\spine-database-api\spinedb_api\import_functions.py", line 157, in import_data
    updated = update_items(*to_update)
  File "c:\data\spine\spine-database-api\spinedb_api\db_mapping_update_mixin.py", line 88, in _update_object_classes
    return self._update_items("object_class", *items)
  File "c:\data\spine\spine-database-api\spinedb_api\db_mapping_update_mixin.py", line 48, in _update_items
    items, ids = self._items_to_update_and_ids(*items)
  File "c:\data\spine\spine-database-api\spinedb_api\db_mapping_update_mixin.py", line 32, in _items_to_update_and_ids
    item["commit_id"] = self.make_commit_id()
  File "c:\data\spine\spine-database-api\spinedb_api\db_mapping_commit_mixin.py", line 45, in make_commit_id
    self._commit_id = self.connection.execute(ins).inserted_primary_key[0]
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute    return meth(self, multiparams, params)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO "commit" (comment, date, user) VALUES (?, ?, ?)]
[parameters: ('', '2021-03-30 12:28:07.237244', 'Importer')]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Process ReturningProcess-10:
Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "c:\data\spine\spine-engine\spine_engine\utils\returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "c:\data\spine\spine-items\spine_items\importer\do_work.py", line 89, in do_work
    success = _import_data_to_url(cancel_on_error, logs_dir, all_data, url, logger)
  File "c:\data\spine\spine-items\spine_items\importer\do_work.py", line 104, in _import_data_to_url
    import_num, import_errors = spinedb_api.import_data(db_map, **data)
  File "c:\data\spine\spine-database-api\spinedb_api\import_functions.py", line 157, in import_data
    updated = update_items(*to_update)
  File "c:\data\spine\spine-database-api\spinedb_api\db_mapping_update_mixin.py", line 88, in _update_object_classes
    return self._update_items("object_class", *items)
  File "c:\data\spine\spine-database-api\spinedb_api\db_mapping_update_mixin.py", line 48, in _update_items
    items, ids = self._items_to_update_and_ids(*items)
  File "c:\data\spine\spine-database-api\spinedb_api\db_mapping_update_mixin.py", line 32, in _items_to_update_and_ids
    item["commit_id"] = self.make_commit_id()
  File "c:\data\spine\spine-database-api\spinedb_api\db_mapping_commit_mixin.py", line 45, in make_commit_id
    self._commit_id = self.connection.execute(ins).inserted_primary_key[0]
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute    return meth(self, multiparams, params)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO "commit" (comment, date, user) VALUES (?, ?, ?)]
[parameters: ('', '2021-03-30 12:28:07.267165', 'Importer')]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 749, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\default.py", line 543, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: Cannot operate on a closed database.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\pool\base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\pool\base.py", line 891, in _reset
    self._reset_agent.rollback()
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1753, in rollback
    self._do_rollback()
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1791, in _do_rollback
    self.connection._rollback_impl()
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 751, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 749, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\default.py", line 543, in do_rollback
    dbapi_connection.rollback()
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) Cannot operate on a closed database.
(Background on this error at: http://sqlalche.me/e/13/f405)
Exception during reset or similar
Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 749, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\default.py", line 543, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: Cannot operate on a closed database.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\pool\base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\pool\base.py", line 891, in _reset
    self._reset_agent.rollback()
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1753, in rollback
    self._do_rollback()
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1791, in _do_rollback
    self.connection._rollback_impl()
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 751, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 749, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "C:\Users\TRTOPI\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\default.py", line 543, in do_rollback
    dbapi_connection.rollback()
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) Cannot operate on a closed database.
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**Comment by manuelma** [comment]
I did something here. Basically just increased the timeout before sqlite gives up on a locked db. It takes *quite a long time* for these importers to run, and the 5 seconds default timeout was largely insufficient. This showcases a sort of misuse of the sqlite dialect as it's clearly not intended to have such concurrency.

Anyways the timeout is now 1800 seconds, so half an hour. Is that enough? I don't know what's the maximum, but can we have importer jobs that last more than that?

**Comment by manuelma** [comment]
@Tasqu please give it a try whenever you get the chance. The dummy project works for me with this fix, in the sense that I just press 'Execute project' and after a while, the run finalizes with no errors or tracebacks.

**Comment by soininen** [comment]
This makes me wonder if we should have an option to disable parallel execution altogether? As @manuelma says sqlite is not designed for parallelism in mind and the Increased timeout merely hides the underlying problem until somebody has even more importers in their project. You can 'disable' parallelism artificially by clever use of DAG connections but I don't thing that is an intuitive solution. We should also encourage users to use more parallelis- friendly databases.

**Comment by jkiviluo** [comment]
> This makes me wonder if we should have an option to disable parallel execution altogether?

Even if we cannot write in parallel to SQLite, there can be great benefit in executing in parallel, since that can take much more time than the writing. (Maybe not in Topi's case). So, I wonder, if we could actually do that clever disabling of parallelism in the writing phase if the DAG sees a SQLite.

**Comment by manuelma** [comment]
> So, I wonder, if we could actually do that clever disabling of parallelism in the writing phase if the DAG sees a SQLite.

It's pretty much happening already without us doing anything about it. One Importer tries to write first and acquires the 'transaction lock'. The next Importers then try to write and see the lock is taken. So they wait on the lock, and when it's released, one of them gets it and they are naturally queued this way.

**Comment by Tasqu** [comment]
@manuelma Ah, here we go. I had to include two different types of dummy data to replicate the bugs my actual parallel imports run into.
[parallel_importer_issues_2.zip](https://github.com/Spine-project/Spine-Toolbox/files/6241492/parallel_importer_issues_2.zip)
The 5d and 3d data include same object classes, and importing them in parallel seems to mess up the other imports. Importing everything in sequence seems to work.

**Comment by manuelma** [comment]
Thanks @Tasqu 

I'm checking. For me it doesn't happen every time, is that the case also for you? In fact, it has happened once in like twenty attempts...

**Comment by Tasqu** [comment]
@manuel Yes, it's highly unreliable, although for me it seemed pretty reliable for the test system. Increasing or decreasing the data size also has an impact on how often it happens. It seems to me that it happens more if multiple imports finish roughly at the same time, but that's just my impression.

**Comment by Tasqu** [comment]
>I'm checking. For me it doesn't happen every time, is that the case also for you? In fact, it has happened once in like twenty attempts...

Could be a PC thing? My personal laptop isn't particularly powerful, so if you're working on a desktop computer it could be that the data is too small for you.

**Comment by manuelma** [comment]
Ok thanks, I think I can work with this.

**Comment by manuelma** [comment]
I'm trying a new thing in latest spinedb_api's master, can you please @Tasqu give it a shot whenever you get the chance? The dummy project number 2 works well for me now. I wasn't able to make it fail after those latest changes.

**Comment by manuelma** [comment]
> This makes me wonder if we should have an option to disable parallel execution altogether?

About this... so the current approach is to use sqlite's builtin transaction lock, with a very large timeout. This is nice in the sense it doesn't require extra coding from us. If it ever proves insufficient, for whatever reason (e.g., the largest allowed timeout is smaller than what we need for our monster importers to finish), we can always implement our own locking mechanism, using `multiprocessing.Lock`. I believe the `Lock` object needs to be managed by the main process, for obvious reasons, so we'd need to pass it around a lot, which is mildly annoying but of course manageable.

**Comment by Tasqu** [comment]
@manuelma Definitely works way better. I don't get the issues with the test system anymore, and my actual use case worked on the first try in full parallel now as well. My input database tests also pass for the parallel imports, so unless there's something not covered by my tests, all data ends up where it should.

I haven't tested my actual use case in full parallel multiple times yet as the imports take a while, but I'll get back to you if I run into further issues.

Closing this issue for now, as everything seems to be working now.

**Comment by manuelma** [comment]
Thanks @Tasqu, actually a very big part of the solution in these cases seems to be providing the test project, the way you did in this issue.

Briefly, thanks to that project I was able to see that there was another sql transaction, created internally by sqlalchemy, sneaking into our writing routine. The 'solution' was to ignore that transaction to regain full control over the transaction lock.
