### ISSUE TITLE
Importer failes for one specific Single Value Object mapping

### ISSUE THREAD

**Issue by jimhommes** [Spine-project/Spine-Toolbox#1348]
I'm not sure how to recreate it so I've attached the project I'm working on. 
[Spine_project_copy.zip](https://github.com/Spine-project/Spine-Toolbox/files/6229533/Spine_project_copy.zip)

After most recent pull 1 sheet fails in the importer. It fails when the sheet "CapacityMarkets" is imported: if unticked it runs smoothly. 
The following error is in the console:
```
Process ReturningProcess-1:
Traceback (most recent call last):
  File "C:\Users\Jimho\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Jimho\AppData\Local\Programs\Python\Python37\lib\site-packages\spine_engine\utils\returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "C:\Users\Jimho\AppData\Local\Programs\Python\Python37\lib\site-packages\spine_items\importer\do_work.py", line 56, in do_work
    table_mappings, table_options, table_column_convert_specs, table_row_convert_specs, max_rows=-1
  File "C:\Users\Jimho\AppData\Local\Programs\Python\Python37\lib\site-packages\spinedb_api\spine_io\importers\reader.py", line 103, in get_mapped_data
    data_source, mappings, header, table, column_convert_fns, row_convert_fns
  File "C:\Users\Jimho\AppData\Local\Programs\Python\Python37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 89, in get_mapped_data
    row_convert_fns = {pivoted_pos_to_index[row]: fn for row, fn in row_convert_fns.items()}
  File "C:\Users\Jimho\AppData\Local\Programs\Python\Python37\lib\site-packages\spinedb_api\import_mapping\generator.py", line 89, in <dictcomp>
    row_convert_fns = {pivoted_pos_to_index[row]: fn for row, fn in row_convert_fns.items()}
KeyError: 1
```
I have no idea what might be causing it - other single value mappings work just fine with the same kind of values. I've tried to delete the mapping and create a new one without luck.

**Comment by jimhommes** [comment]
I've confirmed that it works, thanks!
