### ISSUE TITLE
Bug when removing SpineOpt Plugin

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1399]
1. Create a `Run SpineOpt` Tool into Design View by dragging the `Run SpineOpt` Tool spec from the plugin toolbar on Design View
2. Remove SpineOpt Plugin from menu (Plugins->Manage Plugins... form)
3. Traceback follows

Traceback (most recent call last):
  File "C:\data\GIT\SPINETOOLBOX\spinetoolbox\widgets\project_item_drag.py", line 449, in _remove_specs
    action = self._actions.pop(row)
KeyError: 0
Traceback (most recent call last):
  File "C:\data\GIT\SPINETOOLBOX\spinetoolbox\widgets\project_item_drag.py", line 449, in _remove_specs
    action = self._actions.pop(row)
KeyError: 0

**Comment by PekkaSavolainen** [comment]
A little try-except magic fixed this.
