### ISSUE TITLE
Exception thrown when trying to view metadata in database editor.

### ISSUE THREAD

**Issue by jimhommes** [Spine-project/Spine-Toolbox#1420]
I was trying out importing more data per object parameter value when I encountered this exception. 

In the database viewer/editor, when right-clicking either a value or object and pressing "View metadata" the following exception is thrown:
```
Traceback (most recent call last):
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\base.py", line 1204, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\default.py", line 1044, in _init_statement
    self.cursor = self.create_cursor()
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\default.py", line 1188, in create_cursor
    return self._dbapi_connection.cursor()
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\pool\base.py", line 1000, in cursor
    return self.connection.cursor(*args, **kwargs)
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 20852 and this is thread id 19256.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "e:\dropbox\workspace\spine-toolbox\spinetoolbox\spine_db_editor\widgets\custom_qtableview.py", line 273, in show_value_metadata
    self._spine_db_editor.show_db_map_parameter_value_metadata(db_map_ids)
  File "e:\dropbox\workspace\spine-toolbox\spinetoolbox\spine_db_editor\widgets\spine_db_editor.py", line 618, in show_db_map_parameter_value_metadata
    for db_map, param_val_ids in db_map_ids.items()
  File "e:\dropbox\workspace\spine-toolbox\spinetoolbox\spine_db_editor\widgets\spine_db_editor.py", line 618, in <dictcomp>
    for db_map, param_val_ids in db_map_ids.items()
  File "e:\dropbox\workspace\spine-toolbox\spinetoolbox\spine_db_editor\widgets\spine_db_editor.py", line 610, in _metadata_per_parameter_value
    for x in db_map.query(sq).filter(db_map.in_(sq.c.parameter_value_id, param_val_ids)):
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\spinedb_api\db_mapping_base.py", line 258, in in_
    in_value.create(self.connection, checkfirst=True)
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\sql\schema.py", line 928, in create
    bind._run_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\sql\visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\sql\ddl.py", line 808, in visit_table
    if not create_ok and not self._can_create_table(table):
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\sql\ddl.py", line 737, in _can_create_table
    self.connection, table.name, schema=effective_schema
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1669, in has_table
    connection, "table_info", table_name, schema=schema
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 2183, in _get_table_pragma
    cursor = connection.execute(statement)
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\base.py", line 1178, in _execute_text
    parameters,
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\base.py", line 1207, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\base.py", line 1204, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\default.py", line 1044, in _init_statement
    self.cursor = self.create_cursor()
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\engine\default.py", line 1188, in create_cursor
    return self._dbapi_connection.cursor()
  File "c:\users\jimho\appdata\local\programs\python\python37\lib\site-packages\sqlalchemy\pool\base.py", line 1000, in cursor
    return self.connection.cursor(*args, **kwargs)
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 20852 and this is thread id 19256.
[SQL: PRAGMA main.table_info("in_value_1d06d0d8-a73c-4035-8a0e-1b075f11e156")]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

And I can't find the metadata defined in the importer anywhere.

**Comment by manuelma** [comment]
Should be an easy fix.

**Comment by manuelma** [comment]
The traceback should be gone and metadata should show after above commit. Please reopen if not the case.
