### ISSUE TITLE
Project file becomes corrupt

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1428]
I was editing an exporter in a project. When trying to run the next item after the exporter (not running the exporter), the process started hanging (Toolbox remained responsive). After re-starting Toolbox, it couldn't open the project and Toolbox itself did not open. I was on the last commit made by Pekka (a4a24cde5f7086180105bf2fd6d9539dfaea1316). It did not help to pull the latest and upgrade the requirements.

Here are the stack traces I was getting (the first one should be when the process hang).

```
Exception in thread Thread-745:
Traceback (most recent call last):
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_engine\spine_engine.py", line 205, in run
    self._process_event(event)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_engine\spine_engine.py", line 269, in _process_event
    item_finish_state = ItemExecutionFinishState[state_value]
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\enum.py", line 352, in __getitem__
    return cls._member_map_[name]
KeyError: 'UNDEFINED'

Exception in thread Thread-768:
Traceback (most recent call last):
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_engine\spine_engine.py", line 462, in _execute_item_filtered
    output_resources = item.output_resources(ED.FORWARD)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_engine\project_item\executable_item_base.py", line 150, in output_resources
    }[direction]()
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\exporter_executable_item_base.py", line 102, in _output_resources_forward
    self.name, self._result_files, self._data_dir, self._databases
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\utils.py", line 280, in exported_files_as_resources
    exported_files = _read_exported_files_file(exported_file_path, data_dir)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\utils.py", line 347, in _read_exported_files_file
    relative_path_manifests = json.load(manifests_file)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 937 (char 936)

Exception in thread Thread-757:
Traceback (most recent call last):
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_engine\spine_engine.py", line 205, in run
    self._process_event(event)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_engine\spine_engine.py", line 269, in _process_event
    item_finish_state = ItemExecutionFinishState[state_value]
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\enum.py", line 352, in __getitem__
    return cls._member_map_[name]
KeyError: 'UNDEFINED'

QThread: Destroyed while thread is still running

(spi37) C:\data\SpineToolbox>python spinetoolbox
Traceback (most recent call last):
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "spinetoolbox\__main__.py", line 22, in <module>
    return_code = main()
  File "c:\data\spinetoolbox\spinetoolbox\main.py", line 66, in main
    window.init_project(args.project)
  File "c:\data\spinetoolbox\spinetoolbox\ui_main.py", line 377, in init_project
    self.open_project(project_dir)
  File "c:\data\spinetoolbox\spinetoolbox\ui_main.py", line 466, in open_project
    return self.restore_project(load_dir)
  File "c:\data\spinetoolbox\spinetoolbox\ui_main.py", line 492, in restore_project
    success = self._project.load(self._item_specification_factories, self.item_factories)
  File "c:\data\spinetoolbox\spinetoolbox\project.py", line 241, in load
    self.add_connection(connection, silent=True)
  File "c:\data\spinetoolbox\spinetoolbox\project.py", line 578, in add_connection
    self.notify_resource_changes_to_successors(source)
  File "c:\data\spinetoolbox\spinetoolbox\project.py", line 864, in notify_resource_changes_to_successors
    trigger_resources = item.resources_for_direct_successors()
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\item_base.py", line 328, in resources_for_direct_successors
    self.name, self._exported_files, self.data_dir, self._database_model.items()
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\utils.py", line 280, in exported_files_as_resources
    exported_files = _read_exported_files_file(exported_file_path, data_dir)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\site-packages\spine_items\utils.py", line 347, in _read_exported_files_file
    relative_path_manifests = json.load(manifests_file)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\prokjt\.julia\conda\3\envs\spi37\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 937 (char 936)
```

**Comment by jkiviluo** [comment]
In this case the solution was to delete the directory where the exporter had operated. I had probably manually corrupted a file in there and Toolbox didn't know how to recover. @soininen is still thinking whether we can do more to prevent Toolbox from working in these kinds of situations.

**Comment by soininen** [comment]
Engine should now be a bit more robust if items fail to execute due to some unforeseen complications. Also, file meant for exporter's internal use are now prepended by `.` which hopefully makes users think twice before trying to edit them.

**Comment by jkiviluo** [comment]
I guess we should close?
