### ISSUE TITLE
Data Store fails to clone a database with value transformer

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1429]
I have a project with DS -> DT (value transformation) -> DS. When executing, I get the following Traceback:

```
Process ReturningProcess-1:
Traceback (most recent call last):
  File "lib\site-packages\sqlalchemy\util\_collections.py", line 210, in __getattr__
    return self._data[key]
KeyError: 'type'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "spine_engine\utils\returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "spine_items\data_store\do_work.py", line 44, in do_work
    from_db_map_data = {db_map: export_data(db_map) for db_map in from_db_maps if db_map is not None}
  File "spine_items\data_store\do_work.py", line 44, in <dictcomp>
    from_db_map_data = {db_map: export_data(db_map) for db_map in from_db_maps if db_map is not None}
  File "spinedb_api\export_functions.py", line 77, in export_data
    "object_parameter_values": export_object_parameter_values(db_map, object_parameter_value_ids),
  File "spinedb_api\export_functions.py", line 159, in export_object_parameter_values
    for x in _make_query(db_map, "object_parameter_value_sq", ids)
  File "spinedb_api\export_functions.py", line 91, in _make_query
    sq = getattr(db_map, sq_attr)
  File "spinedb_api\db_mapping_base.py", line 1270, in object_parameter_value_sq
    self.parameter_value_sq.c.type,
  File "lib\site-packages\sqlalchemy\util\_collections.py", line 212, in __getattr__
    raise AttributeError(key)
AttributeError: type
Exception during reset or similar
Traceback (most recent call last):
  File "lib\site-packages\sqlalchemy\engine\base.py", line 749, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File lib\site-packages\sqlalchemy\engine\default.py", line 558, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: Cannot operate on a closed database.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib\site-packages\sqlalchemy\pool\base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "lib\site-packages\sqlalchemy\pool\base.py", line 891, in _reset
    self._reset_agent.rollback()
  File "lib\site-packages\sqlalchemy\engine\base.py", line 1751, in rollback
    self._do_rollback()
  File "lib\site-packages\sqlalchemy\engine\base.py", line 1789, in _do_rollback
    self.connection._rollback_impl()
  File "lib\site-packages\sqlalchemy\engine\base.py", line 751, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "lib\site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "lib\site-packages\sqlalchemy\engine\base.py", line 749, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "lib\site-packages\sqlalchemy\engine\default.py", line 558, in do_rollback
    dbapi_connection.rollback()
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) Cannot operate on a closed database.
(Background on this error at: http://sqlalche.me/e/13/f405)
Exception during reset or similar
Traceback (most recent call last):
  File "lib\site-packages\sqlalchemy\pool\base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "lib\site-packages\sqlalchemy\pool\base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "lib\site-packages\sqlalchemy\engine\default.py", line 558, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: Cannot operate on a closed database.
```

**Comment by soininen** [comment]
Fixed.
