### ISSUE TITLE
Creating new Tool specification fails

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1442]
1. Create a new project
2. Add Tool item
3. Double click the Tool
4. Name the spec, select Tool type (e.g. Python), create an empty Main program file
5. Hit **Ctrl-S** to save

```
Traceback (most recent call last):
  File "items\spine_items\tool\widgets\tool_specification_editor_window.py", line 173, in _save
    if not super()._save():
  File "toolbox\spinetoolbox\project_item\specification_editor_window.py", line 188, in _save
    self.item.set_specification(spec)
  File "toolbox\spinetoolbox\project_item\project_item.py", line 180, in set_specification
    self._toolbox.undo_stack.push(SetItemSpecificationCommand(self, specification, self.undo_specification()))
  File "items\spine_items\tool\tool.py", line 226, in undo_specification
    undo_spec.execute_in_work = self.execute_in_work
AttributeError: 'NoneType' object has no attribute 'execute_in_work'
```

**Comment by PekkaSavolainen** [comment]
I just cherry-picked a possible fix from my branch to master

**Comment by manuelma** [comment]
Thanks guys I introduced this yesterday when solving issues with saving a spec. The fix works, I just rearranged the code a little bit to save one `if`.
