### ISSUE TITLE
GDX exporter fails silently with poorly designed spec

### ISSUE THREAD

**Issue by ererkka** [Spine-project/Spine-Toolbox#1535]
If some dimensions are poorly mapped in a GDX export spec and there is ‘map’ in some cell, the execution does not proceed but there is this traceback in the console:

```
Process ReturningProcess-1:
Traceback (most recent call last):
  File "C:\Users\ERERKKA\Miniconda3\envs\spinetoolbox\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\users\ererkka\onedrive - teknologian tutkimuskeskus vtt\projects\spine\spine-engine\spine_engine\utils\returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "c:\users\ererkka\onedrive - teknologian tutkimuskeskus vtt\projects\spine\spine-items\spine_items\exporter\do_work.py", line 71, in do_work
    write(database_map, writer, *mappings, empty_data_header=header_always)
  File "c:\users\ererkka\onedrive - teknologian tutkimuskeskus vtt\projects\spine\spine-database-api\spinedb_api\spine_io\exporters\writer.py", line 46, in write
    break
  File "C:\Users\ERERKKA\Miniconda3\envs\spinetoolbox\lib\contextlib.py", line 120, in __exit__
    next(self.gen)
  File "c:\users\ererkka\onedrive - teknologian tutkimuskeskus vtt\projects\spine\spine-database-api\spinedb_api\spine_io\exporters\writer.py", line 124, in _new_table
    writer.finish_table()
  File "c:\users\ererkka\onedrive - teknologian tutkimuskeskus vtt\projects\spine\spine-database-api\spinedb_api\spine_io\exporters\gdx_writer.py", line 59, in finish_table
    self._gdx_file[self._current_table_name] = set_
  File "C:\Users\ERERKKA\Miniconda3\envs\spinetoolbox\lib\site-packages\gdx2py\gdxfile.py", line 184, in __setitem__
    self._write_symbol(name, symbol)
  File "C:\Users\ERERKKA\Miniconda3\envs\spinetoolbox\lib\site-packages\gdx2py\gdxfile.py", line 428, in _write_symbol
    for key, value in symbol:
  File "C:\Users\ERERKKA\Miniconda3\envs\spinetoolbox\lib\site-packages\gdx2py\gams.py", line 234, in __next__
    return key, float(val)
ValueError: could not convert string to float: 'map'
```

The app does not crash and execution can be cancelled.

## Expected

This would raise a warning of some sort when saving the exporter spec.

**Comment by ererkka** [comment]
Maybe related #891

**Comment by soininen** [comment]
More like related to #1483. We should indeed fail more graciously in cases like this.

**Comment by soininen** [comment]
This and some other pathological mappings should not crash exporter execution anymore.
