### ISSUE TITLE
IndexError with when only some index names defined in Importer 

### ISSUE THREAD

**Issue by ererkka** [Spine-project/Spine-Toolbox#1542]
Creating an import mapping where only some index levels have names leads to an IndexError when executing the Importer:

```
Traceback (most recent call last):
  File "...\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "...\spine-engine\spine_engine\utils\returning_process.py", line 41, in run
    result = self._target(*self._args, **self._kwargs)
  File "...\spine-items\spine_items\importer\do_work.py", line 55, in do_work
    data, errors = connector.get_mapped_data(
  File "...\spine-database-api\spinedb_api\spine_io\importers\reader.py", line 112, in get_mapped_data
    data, t_errors = get_mapped_data(
  File "...\spine-database-api\spinedb_api\import_mapping\generator.py", line 125, in get_mapped_data
    _make_parameter_values(mapped_data)
  File "...\spine-database-api\spinedb_api\import_mapping\generator.py", line 229, in _make_parameter_values
    row[value_pos] = _parameter_value_from_dict(value)
  File "...\spine-database-api\spinedb_api\import_mapping\generator.py", line 242, in _parameter_value_from_dict
    _apply_index_names(map_, index_names)
  File "...\spine-database-api\spinedb_api\import_mapping\generator.py", line 297, in _apply_index_names
    _apply_index_names(v, index_names[1:])
  File "...\spine-database-api\spinedb_api\import_mapping\generator.py", line 297, in _apply_index_names
    _apply_index_names(v, index_names[1:])
  File "...\spine-database-api\spinedb_api\import_mapping\generator.py", line 294, in _apply_index_names
    map_.index_name = index_names[0]
IndexError: list index out of range

```

This apparently because the index names list is reduced to `[]` before all indices have been processed. 

You can try this out with https://github.com/ererkka/spinetoolbox-Importer-IndexError.

**Comment by soininen** [comment]
This bug should now be fixed. Please update `spinedb_api` to get the fix. Thanks for the example project! It helped in debugging the problem quite a bit.
