### ISSUE TITLE
Closing a MySQL database raises AttributeError

### ISSUE THREAD

**Issue by ererkka** [Spine-project/Spine-Toolbox#1570]
Closing the database editor to a MySQL database, the following error is raised:

    AttributeError: 'Connection' object has no attribute '_Connection__connection'

<details><summary>Full traceback</summary>

```
Traceback (most recent call last):
  File "C:\Users\ERERKKA\OneDrive - Teknologian Tutkimuskeskus VTT\Projects\Spine\SpineToolbox-master\spinetoolbox\spine_db_fetcher.py", line 143, in _fetch_more
    self._do_fetch_more(item_type, parent)
  File "C:\Users\ERERKKA\OneDrive - Teknologian Tutkimuskeskus VTT\Projects\Spine\SpineToolbox-master\spinetoolbox\helpers.py", line 130, in new_function
    return func(*args, **kwargs)
  File "C:\Users\ERERKKA\OneDrive - Teknologian Tutkimuskeskus VTT\Projects\Spine\SpineToolbox-master\spinetoolbox\spine_db_fetcher.py", line 152, in _do_fetch_more
    chunk = next(iterator, [])
  File "C:\Users\ERERKKA\OneDrive - Teknologian Tutkimuskeskus VTT\Projects\Spine\SpineToolbox-master\spinetoolbox\spine_db_fetcher.py", line 224, in _get_db_items
    it = (x._asdict() for x in query.yield_per(query_chunk_size).enable_eagerloads(False))
  File "C:\Users\ERERKKA\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\orm\query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "C:\Users\ERERKKA\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\orm\query.py", line 3556, in _execute_and_instances
    conn = self._get_bind_args(
  File "C:\Users\ERERKKA\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\orm\query.py", line 3571, in _get_bind_args
    return fn(
  File "C:\Users\ERERKKA\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\orm\query.py", line 3550, in _connection_from_session
    conn = self.session.connection(**kw)
  File "C:\Users\ERERKKA\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\orm\session.py", line 1142, in connection
    return self._connection_for_bind(
  File "C:\Users\ERERKKA\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\orm\session.py", line 1154, in _connection_for_bind
    conn = engine._contextual_connect(**kw)
  File "C:\Users\ERERKKA\Miniconda3\envs\spinetoolbox\lib\site-packages\sqlalchemy\engine\base.py", line 524, in _contextual_connect
```
</details>

**Comment by ererkka** [comment]
Error is raised on https://github.com/Spine-project/Spine-Toolbox/blob/75b087aa87fccfebd2d8ae130492025f262c1e50/spinetoolbox/spine_db_fetcher.py#L224 

This might be related to #1568 as `item_type == 'parameter_definition'` when this occurs.

**Comment by ererkka** [comment]
This is raised in `SpineDBFetcher._get_db_items()` when `item_type == 'parameter_value'`. I wonder why data is fetched when the database is being closed.

**Comment by ererkka** [comment]
Ok, great. The error seem not to be a crashing one, but anything appearing to the console is always worrying...

**Comment by manuelma** [comment]
I have merged my changes but my guess is this TB still happens, because we don't stop the fetching when closing the form (although we do close the db connection.) 
The fetcher thread knows nothing about the form being closed because it's a different thread. One idea would be to tell the fetcher thread to stop querying and then wait on a signal before closing the db connection.

**Comment by soininen** [comment]
FYI, I'm currently looking into solving this issue with something similar to what @manuelma is describing but with `QMutex`es.

**Comment by soininen** [comment]
Looks like the original issue reported by @ererkka is gone even without the above commits. The changes, however, fix some other issues related to closing DB editor tabs so I think it is reasonable to merge them to master.

**Comment by manuelma** [comment]
Amazing job @soininen 

I looked at the code briefly and seems top quality. I suggest we close this now.

**Comment by ererkka** [comment]
Thank you!
