### ISSUE TITLE
TypeError when using the importer filter with a number

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1591]
I have an object class mapping with parameter values, and I tried to put `1` in the filter for the parameter value. Running the importer results in a traceback:

```
Traceback (most recent call last):
  File "/home/manuel/miniconda3/envs/spinetoolbox/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/manuel/Codes/spine/spine-engine/spine_engine/utils/returning_process.py", line 82, in run
    result = self._target(*self._args, **self._kwargs)
  File "/home/manuel/Codes/spine/spine-items/spine_items/importer/do_work.py", line 55, in do_work
    data, errors = connector.get_mapped_data(
  File "/home/manuel/Codes/spine/Spine-Database-API/spinedb_api/spine_io/importers/reader.py", line 132, in get_mapped_data
    data, t_errors = get_mapped_data(
  File "/home/manuel/Codes/spine/Spine-Database-API/spinedb_api/import_mapping/generator.py", line 82, in get_mapped_data
    mapping.import_row(row, read_state, mapped_data)
  File "/home/manuel/Codes/spine/Spine-Database-API/spinedb_api/import_mapping/import_mapping.py", line 235, in import_row
    self.child.import_row(source_row, state, mapped_data, errors=errors)
  File "/home/manuel/Codes/spine/Spine-Database-API/spinedb_api/import_mapping/import_mapping.py", line 235, in import_row
    self.child.import_row(source_row, state, mapped_data, errors=errors)
  File "/home/manuel/Codes/spine/Spine-Database-API/spinedb_api/import_mapping/import_mapping.py", line 235, in import_row
    self.child.import_row(source_row, state, mapped_data, errors=errors)
  [Previous line repeated 7 more times]
  File "/home/manuel/Codes/spine/Spine-Database-API/spinedb_api/import_mapping/import_mapping.py", line 217, in import_row
    elif self._filter_re is None or self._filter_re.search(source_data) is not None:
TypeError: expected string or bytes-like object
```

**Comment by soininen** [comment]
Looks like the mapping is trying to apply the filter to the bytes object that is the JSON representation of the value in database. I guess we need to cast it to string here.

**Comment by manuelma** [comment]
It's applying the filter to a float, so yeah, pretty much that. I think the fix can be as simple as `self._filter_re.search(str(source_data))`, but maybe you have a better idea?

**Comment by soininen** [comment]
I haven't really looked into this, so I don't have many ideas. One thing that comes to mind is if `source_data` has already ran through `from_database`, then it can be a `Map` or `TimeSeries` or whatever. I'm unsure how `str()` would deal with it.

**Comment by soininen** [comment]
Disregard what I said about bytes since I didn't realize that we're actually talking about importer here so the data is not yet in the database. I guess `str()` would be way to go here if we've already cast `source_data` to `float`, `boolean` or `datetime` or whatever.

**Comment by manuelma** [comment]
Ok, I will go with that. Thanks!
