### ISSUE TITLE
Running a Tool in persistent console twice fails

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1601]
This happens when executing the same Tool in persistent console back-to-back.

```
Exception in thread Thread-26:
Traceback (most recent call last):
  File "C:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\data\GIT\SPINEENGINE\spine_engine\spine_engine.py", line 588, in _execute_item_filtered
    item_finish_state = item.execute(filtered_forward_resources, filtered_backward_resources)
  File "C:\data\GIT\SPINEITEMS\spine_items\tool\executable_item.py", line 465, in execute
    self._tool_instance.prepare(expanded_args)
  File "C:\data\GIT\SPINEITEMS\spine_items\tool\tool_instance.py", line 238, in prepare
    self.exec_mngr = PythonPersistentExecutionManager(
  File "C:\data\GIT\SPINEENGINE\spine_engine\execution_managers\persistent_execution_manager.py", line 611, in __init__
    self._persistent_manager = _persistent_manager_factory.new_persistent_manager(
  File "C:\data\GIT\SPINEENGINE\spine_engine\execution_managers\persistent_execution_manager.py", line 433, in new_persistent_manager
    pm.restart()
AttributeError: 'PythonPersistentManager' object has no attribute 'restart'
```

**Comment by PekkaSavolainen** [comment]
Traceback is gone and execution works as expected again. Please reopen if I missed something here.
