### ISSUE TITLE
`Export` option for database entities from the DB Editor fails for some entities.

### ISSUE THREAD

**Issue by Tasqu** [Spine-project/Spine-Toolbox#1641]
![image](https://user-images.githubusercontent.com/77660814/150785766-9f5fe279-7043-410d-bc68-68eb96071d2f.png)

Trying to export database entities via the drop-down menu in the DB Editor occasionally fails, as if nothing was attempted. However, the console displays the following traceback:
```
Traceback (most recent call last):
  File "c:\data\spine\spine-toolbox\spinetoolbox\spine_db_editor\widgets\custom_qtreeview.py", line 188, in export_selected
    self._spine_db_editor.export_selected(self._selected_indexes)
  File "c:\data\spine\spine-toolbox\spinetoolbox\spine_db_editor\widgets\tree_view_mixin.py", line 125, in export_selected
    parcel.full_push_object_ids(db_map_obj_ids)
  File "c:\data\spine\spine-toolbox\spinetoolbox\spine_db_parcel.py", line 247, in full_push_object_ids
    db_map_ids = {db_map: ids for db_map, ids in db_map_ids.items() if not param_val_ids[db_map]}
  File "c:\data\spine\spine-toolbox\spinetoolbox\spine_db_parcel.py", line 247, in <dictcomp>
    db_map_ids = {db_map: ids for db_map, ids in db_map_ids.items() if not param_val_ids[db_map]}
KeyError: <spinedb_api.diff_db_mapping.DiffDatabaseMapping object at 0x000001C6BB372C70>
```
It seems that mostly, entire object/relationship classes are broken in this manner, but I was able to locate a few exceptions. I tried searching for some common denominator for the broken entities, but unfortunately didn't find anything conclusive.

**Comment by manuelma** [comment]
Hi @Tasqu thanks for this. Can you maybe provide an example where it always fails?

**Comment by Tasqu** [comment]
@manuelma not using the latest database version, seems like it has been updated recently. I can easily re-create one that should be usable for demonstrating this, but I have a meeting in 10 minutes so this has to wait a bit 😄 I'll try and remember to upload some example afterwards

**Comment by manuelma** [comment]
Thank you @Tasqu ! Of course, no hurries, whenever you get the chance...

**Comment by Tasqu** [comment]
Here's an example datastore. Trying to export e.g. the `building_loads` object via
![image](https://user-images.githubusercontent.com/77660814/158591771-803b3586-8db3-4490-89d0-e3ba4db41fe5.png)
results in a traceback similar to the above for me. I had to zip the sqlite, as github didn't allow including an .sqlite directly
[Data_and_definitions.zip](https://github.com/Spine-project/Spine-Toolbox/files/8262142/Data_and_definitions.zip)

**Comment by manuelma** [comment]
Should work better after above commit.
