### ISSUE TITLE
Importer Traceback when import Map while the values are None

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1646]
Consider the following input table:

|             |        |       | parameter |
|-------------|--------|-------|-----------|
| alternavite | object | index | my_param  |
| Base        | obj1   | T1    |           |
| Base        | obj1   | T2    |           |

and the following import mapping for Map type object parameter values:

![mappings_for_issue](https://user-images.githubusercontent.com/19147159/151778034-64c33dd4-9d5f-4cbc-9777-e90cd5248bcc.png)

Executing Importer results in a Traceback:

```
Traceback (most recent call last):
File "multiprocessing\process.py", line 315, in _bootstrap
self.run()
File "spine_engine\utils\returning_process.py", line 46, in run
result = self._target(*self._args, **self._kwargs)
File "spine_items\importer\do_work.py", line 65, in do_work
data, errors = connector.get_mapped_data(
File "spinedb_api\spine_io\importers\reader.py", line 132, in get_mapped_data
data, t_errors = get_mapped_data(
File "spinedb_api\import_mapping\generator.py", line 126, in get_mapped_data
_make_parameter_values(mapped_data)
File "spinedb_api\import_mapping\generator.py", line 233, in _make_parameter_values
row[value_pos] = _parameter_value_from_dict(value)
File "spinedb_api\import_mapping\generator.py", line 247, in _parameter_value_from_dict
map_ = _table_to_map(d["data"], compress=d.get("compress", False))
KeyError: 'data'
```

Expected  behavior is to import the data successfully and just omit the Map value since it is clearly not defined in the input table.

**Comment by soininen** [comment]
Fixed.
