### ISSUE TITLE
Traceback from Importer when importing pivoted data from empty table

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1648]
Trying to import pivoted data from an empty table raises a Traceback:

```
Traceback (most recent call last):
File "multiprocessing\process.py", line 315, in _bootstrap
self.run()
File "spine_engine\utils\returning_process.py", line 46, in run
result = self._target(*self._args, **self._kwargs)
File "spine_items\importer\do_work.py", line 65, in do_work
data, errors = connector.get_mapped_data(
File "spinedb_api\spine_io\importers\reader.py", line 132, in get_mapped_data
data, t_errors = get_mapped_data(
File "spinedb_api\import_mapping\generator.py", line 85, in get_mapped_data
unpivoted_rows, pivoted_pos, non_pivoted_pos, unpivoted_column_pos = _unpivot_rows(
File "\spinedb_api\import_mapping\generator.py", line 202, in _unpivot_rows
pivoted_rows = [rows[pos] for pos in pivoted_pos]
File "spinedb_api\import_mapping\generator.py", line 202, in <listcomp>
pivoted_rows = [rows[pos] for pos in pivoted_pos]
IndexError: list index out of range
```

**Comment by soininen** [comment]
Fixed.
