### ISSUE TITLE
Using Jupyter console hangs execution

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1661]
Trying to execute a Python Tool using a Jupyter console hangs execution. When running Toolbox in debugger, I get the following Traceback:

```
Traceback (most recent call last):
File "spinetoolbox\spine_engine_worker.py", line 221, in do_work
self._process_event(event_type, data)
File spinetoolbox\spine_engine_worker.py", line 241, in _process_event
handler(data)
File "spinetoolbox\spine_engine_worker.py", line 290, in _handle_kernel_execution_msg
item.jupyter_console_requested.emit(msg["filter_id"], msg["kernel_name"], msg["connection_file"])
AttributeError: 'Tool' object has no attribute 'jupyter_console_requested'
```

Looks like we've broken something.

**Comment by manuelma** [comment]
Will fix.

**Comment by manuelma** [comment]
Should be fixed by https://github.com/Spine-project/Spine-Toolbox/commit/a7fdcd730a38bcff189e94c9ba16b4d2f653f18a

**Comment by manuelma** [comment]
Thanks for the heads up!
