### ISSUE TITLE
Displaying of multiple execution consoles in parallel execution not working correctly

### ISSUE THREAD

**Issue by DillonJ** [Spine-project/Spine-Toolbox#1665]
Edit: I updated this issue to capture the precise problem - there were a few things going on.

When I try and run a simple worflow - a Spine DB with scenarios using SpineOpt, it does not work as expected and I see many many many TBs repeated in the toolbox repeated as the executions run and I only see one console of the multiple parallel executions, which appear to be in progress, but their console output cannot be seen.

![image](https://user-images.githubusercontent.com/7080191/158055336-86e29311-2a1b-4e8f-b380-f28dc2815aaf.png)

Console output:

```julia
Traceback (most recent call last):
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\ui_main.py", line 2324, in _add_persistent_stdout
    self._get_console(item, filter_id).add_stdout(data)
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\ui_main.py", line 2333, in _get_console
    return self._item_consoles[item][filter_id]
KeyError: 'S1 - Run2'
Traceback (most recent call last):
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\ui_main.py", line 2324, in _add_persistent_stdout
    self._get_console(item, filter_id).add_stdout(data)
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\ui_main.py", line 2333, in _get_console
    return self._item_consoles[item][filter_id]
KeyError: 'S1 - Run2'
Traceback (most recent call last):
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\ui_main.py", line 2324, in _add_persistent_stdout
    self._get_console(item, filter_id).add_stdout(data)
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\ui_main.py", line 2333, in _get_console
    return self._item_consoles[item][filter_id]
KeyError: 'S2 - Run2'
Traceback (most recent call last):
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\ui_main.py", line 2324, in _add_persistent_stdout
    self._get_console(item, filter_id).add_stdout(data)
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\ui_main.py", line 2333, in _get_console
    return self._item_consoles[item][filter_id]
KeyError: 'S2 - Run2'
Traceback (most recent call last):
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\ui_main.py", line 2324, in _add_persistent_stdout
    self._get_console(item, filter_id).add_stdout(data)
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\ui_main.py", line 2333, in _get_console
    return self._item_consoles[item][filter_id]
KeyError: 'S1 - Run2'
Traceback (most recent call last):
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\ui_main.py", line 2324, in _add_persistent_stdout
    self._get_console(item, filter_id).add_stdout(data)
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\ui_main.py", line 2333, in _get_console
    return self._item_consoles[item][filter_id]
KeyError: 'S2 - Run2'
Traceback (most recent call last):
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\ui_main.py", line 2324, in _add_persistent_stdout
    self._get_console(item, filter_id).add_stdout(data)
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\ui_main.py", line 2333, in _get_console
    return self._item_consoles[item][filter_id]
KeyError: 'S1 - Run2'
Traceback (most recent call last):
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\ui_main.py", line 2324, in _add_persistent_stdout
    self._get_console(item, filter_id).add_stdout(data)
  File "C:\Workspace\Spine\Spine-Toolbox\spinetoolbox\ui_main.py", line 2333, in _get_console
    return self._item_consoles[item][filter_id]
KeyError: 'S2 - Run2'
```

**Comment by DillonJ** [comment]
Ok, so an update on this :

There are two problems - 1. is that the "one scenario per alternative" function of the "scenario generator" doesn't include the base scenario so it's not really very useful most of the time when you want the base scenario included? Maybe we need another option "designate base scenario" or something? 

The other issue is that there is some problem with the execution consoles - I only see one execution and am getting the above TBs in console suggesting there is some problem displaying the multiple consoles. This is what I see in TB:
You can see that only one execution appears in the top right but from the log bottom left, it looks like there are three executions in progress (but I have no way of seeing their output)

![image](https://user-images.githubusercontent.com/7080191/158054558-db347fe9-c489-4625-8316-6ce556b22154.png)

**Comment by manuelma** [comment]
Thank you @DillonJ and sorry for the troubles. As you point out, this was just a console visualization issue and is fixed in latest master.

**Comment by manuelma** [comment]
We need to add a tests now.

**Comment by manuelma** [comment]
I added a couple of tests to make sure all the scenarios are listed and their consoles are shown when selected in the view. Closing.
