### ISSUE TITLE
Importer's 'Purge before writing' creates a Traceback when the Importer is run in parallel

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1679]
Are all instances of an Importer which is run in parallel trying to purge the target database at the same time? Every time I try to execute such a workflow I get an Traceback similar to the one below:

```
Process ReturningProcess-2:
Traceback (most recent call last):
  File "lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "lib\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: parameter_definition_tag

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "spine_engine\utils\returning_process.py", line 47, in run
    result = self._target(*self._args, **self._kwargs)
  File "spine_items\importer\do_work.py", line 105, in do_work
    success = _import_data_to_url(
  File "spine_items\importer\do_work.py", line 115, in _import_data_to_url
    spinedb_api.create_new_spine_database(url)
  File "spinedb_api\helpers.py", line 692, in create_new_spine_database
    meta.drop_all()
  File "lib\site-packages\sqlalchemy\sql\schema.py", line 4690, in drop_all
    bind._run_visitor(
  File "lib\site-packages\sqlalchemy\engine\base.py", line 2095, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "lib\site-packages\sqlalchemy\engine\base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "lib\site-packages\sqlalchemy\sql\visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "lib\site-packages\sqlalchemy\sql\ddl.py", line 955, in visit_metadata
    self.traverse_single(
  File "lib\site-packages\sqlalchemy\sql\visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "lib\site-packages\sqlalchemy\sql\ddl.py", line 1018, in visit_table
    self.connection.execute(DropTable(table))
  File "lib\site-packages\sqlalchemy\engine\base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "lib\site-packages\sqlalchemy\sql\ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "lib\site-packages\sqlalchemy\engine\base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "lib\site-packages\sqlalchemy\engine\base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "lib\site-packages\sqlalchemy\engine\base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "lib\site-packages\sqlalchemy\engine\base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "lib\site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: parameter_definition_tag
[SQL: 
DROP TABLE parameter_definition_tag]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

The table name after 'no such table' changes from execution to execution.

**Comment by soininen** [comment]
Should be fixed by #1768
