### ISSUE TITLE
Traceback when closing DB editor with multiple databases

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1704]
I'm using a View project item to gain access to two different databases simultaneously. Sometimes, e.g. after adding a new paramter to an object class, when I close the editor and Discard changes I get the following Traceback:

```
Traceback (most recent call last):
  File "spinetoolbox\mvcmodels\minimal_tree_model.py", line 339, in hasChildren
    return parent_item.has_children()
  File "spinetoolbox\mvcmodels\minimal_tree_model.py", line 38, in has_children
    if self.can_fetch_more():
  File "spinetoolbox\spine_db_editor\mvcmodels\entity_tree_item.py", line 257, in can_fetch_more
    return super().can_fetch_more() or self._can_fetch_members_item()
  File "spinetoolbox\spine_db_editor\mvcmodels\entity_tree_item.py", line 248, in _can_fetch_members_item
    return self.is_group() and not self._has_members_item
  File "spinetoolbox\spine_db_editor\mvcmodels\entity_tree_item.py", line 236, in is_group
    return any(self.db_map_data_field(db_map, "group_id") is not None for db_map in self.db_maps)
  File "spinetoolbox\spine_db_editor\mvcmodels\entity_tree_item.py", line 236, in <genexpr>
    return any(self.db_map_data_field(db_map, "group_id") is not None for db_map in self.db_maps)
  File "spinetoolbox\spine_db_editor\mvcmodels\multi_db_tree_item.py", line 186, in db_map_data_field
    return self.db_map_data(db_map).get(field, default)
  File "spinetoolbox\spine_db_editor\mvcmodels\multi_db_tree_item.py", line 182, in db_map_data
    return self.db_mngr.get_item(db_map, self.item_type, id_)
  File "spinetoolbox\spine_db_manager.py", line 676, in get_item
    worker = self._get_worker(db_map)
  File "spinetoolbox\spine_db_manager.py", line 257, in _get_worker
    return self._workers[db_map]
KeyError: <spinedb_api.diff_db_mapping.DiffDatabaseMapping object at 0x000001CDACFFC7F0>
```

**Comment by soininen** [comment]
Fixed.
