### ISSUE TITLE
Traceback when removing parameter value lists in DB editor

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1705]
I noticed there are Tracebacks when executing Toolbox unit tests even though the tests pass superficially. Turns out these are actual bugs in DB editor.

One of the issues is removing a parameter value list which results in the following Traceback:

```
Traceback (most recent call last):
  File "spinetoolbox\spine_db_manager.py", line 211, in <lambda>
    signal.connect(lambda db_map_data, item_type=item_type: self.cache_items(item_type, db_map_data))
  File "spinetoolbox\spine_db_manager.py", line 301, in cache_items
    raise e
  File "spinetoolbox\spine_db_manager.py", line 299, in cache_items
    self._cache.setdefault(db_map, {}).setdefault(item_type, {})[item["id"]] = CacheItem(**item)
KeyError: 'id'
```

Note: the last line is probably 298 since I've inserted some debuging code there.

**Comment by soininen** [comment]
Fixed.
