### ISSUE TITLE
Exporter Traceback when writing unmappable characters to CSV files

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1716]
Apparently some special unicode characters in database cause CSV output to fail with a Traceback:

```
Traceback (most recent call last):
  File "Python-3.8\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "spine_engine\utils\returning_process.py", line 47, in run
    result = self._target(*self._args, **self._kwargs)
  File "spine_items\exporter\do_work.py", line 74, in do_work
    write(database_map, writer, *mappings, empty_data_header=header_always, group_fns=group_fns)
  File "spinedb_api\spine_io\exporters\writer.py", line 55, in write
    write_more = writer.write_row(row)
  File "spinedb_api\spine_io\exporters\csv_writer.py", line 69, in write_row
    self._out.writerow(row)
  File "Python-3.8\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\ufeff' in position 7: character maps to <undefined>
```

I think we should at least catch these exceptions in `csv_writer` but don't know what to do with them.

**Comment by Ahnaf-Ahmed** [comment]
This occurs because of the encoding when the file is opened to be written to. This issue can be fixed by changing the line `self._file = open(self._file_name, "a", newline="")` to `self._file = open(self._file_name, "a", newline="", encoding="utf-8")` in the start_table() method of csv_writer.py of spinedb-api (src\spinedb-api\spinedb_api\spine_io\exporters\csv_writer.py). I was looking into submitting a PR but could not get tests to run so I'm noting it here.
