### ISSUE TITLE
Installing requirements.txt results in broken Toolbox

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1718]
Running `python -mpip install -r requirements.txt` gives broken dependencies. You get the following Traceback when running Toolbox:
```
Traceback (most recent call last):
File "lib\runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "spinetoolbox\__main__.py", line 20, in <module>
from spinetoolbox.main import main
File "spinetoolbox\main.py", line 37, in <module>
from .ui_main import ToolboxUI
File "spinetoolbox\ui_main.py", line 59, in <module>
from spine_engine.load_project_items import load_item_specification_factories
File "spine_engine\__init__.py", line 12, in <module>
from .spine_engine import ExecutionDirection, SpineEngine, SpineEngineState, ItemExecutionFinishState
File "spine_engine\spine_engine.py", line 25, in <module>
from dagster import (
File "lib\site-packages\dagster\__init__.py", line 155, in <module>
from dagster.core.launcher import DefaultRunLauncher
File "lib\site-packages\dagster\core\launcher\__init__.py", line 1, in <module>
from .base import LaunchRunContext, RunLauncher
File "lib\site-packages\dagster\core\launcher\base.py", line 7, in <module>
from dagster.core.workspace.workspace import IWorkspace
File "lib\site-packages\dagster\core\workspace\__init__.py", line 1, in <module>
from .context import IWorkspaceProcessContext, WorkspaceProcessContext
File "lib\site-packages\dagster\core\workspace\context.py", line 13, in <module>
from dagster.core.host_representation import (
File "lib\site-packages\dagster\core\host_representation\__init__.py", line 49, in <module>
from .repository_location import (
File "lib\site-packages\dagster\core\host_representation\repository_location.py", line 12, in <module>
from dagster.api.snapshot_execution_plan import sync_get_external_execution_plan_grpc
File "lib\site-packages\dagster\api\snapshot_execution_plan.py", line 9, in <module>
from dagster.grpc.types import ExecutionPlanSnapshotArgs
File "lib\site-packages\dagster\grpc\__init__.py", line 11, in <module>
from .client import DagsterGrpcClient, ephemeral_grpc_api_client
File "lib\site-packages\dagster\grpc\client.py", line 18, in <module>
from .__generated__ import DagsterApiStub, api_pb2
File "lib\site-packages\dagster\grpc\__generated__\__init__.py", line 6, in <module>
from . import api_pb2
File "lib\site-packages\dagster\grpc\__generated__\api_pb2.py", line 33, in <module>
_EMPTY = _descriptor.Descriptor(
File "lib\site-packages\google\protobuf\descriptor.py", line 313, in __new__
_message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
1. Downgrade the protobuf package to 3.20.x or lower.
2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by soininen** [comment]
Fixed.
