### ISSUE TITLE
pyreadline package as a 'semi' requirement

### ISSUE THREAD

**Issue by PekkaSavolainen** [Spine-project/Spine-Toolbox#1722]
In https://github.com/Spine-project/spine-engine/blob/e9803d8b2dcf574e0a311a92c55d831df8b82e5b/spine_engine/execution_managers/spine_repl.py#L18 we try to import package [pyreadline](https://pypi.org/project/pyreadline/), right? I don't know how long I've had it installed on my Python's (3.7 & 3.8) but for some reason it just recently started giving me problems. The reason is quite clear though, the package has not been updated in 7 years and it's been tested only with Windows 2000 and XP. The problem I had was similar to [this SO question](https://stackoverflow.com/questions/68798700/python-terminal-gives-error-after-opening) but in my case starting a Python REPL fails with a MemoryError and it takes about 40 minutes to start the REPL. Here's the TB (happens on both pure and Conda Python's):

```
(toolbox37) C:\>python
Python 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
Failed calling sys.__interactivehook__
Traceback (most recent call last):
  File "C:\Users\ttepsa\.conda\envs\toolbox37\lib\site.py", line 439, in register_readline
    readline.read_history_file(history)
  File "C:\Users\ttepsa\.conda\envs\toolbox37\lib\site-packages\pyreadline\rlmain.py", line 165, in read_history_file
    self.mode._history.read_history_file(filename)
  File "C:\Users\ttepsa\.conda\envs\toolbox37\lib\site-packages\pyreadline\lineeditor\history.py", line 83, in read_history_file
    self.add_history(lineobj.ReadLineTextBuffer(ensure_unicode(line.rstrip())))
  File "C:\Users\ttepsa\.conda\envs\toolbox37\lib\site-packages\pyreadline\lineeditor\lineobj.py", line 403, in __init__
    super(ReadLineTextBuffer, self).__init__(txtstr, point, mark)
  File "C:\Users\ttepsa\.conda\envs\toolbox37\lib\site-packages\pyreadline\lineeditor\lineobj.py", line 185, in __init__
    self._insert_text(txtstr)
  File "C:\Users\ttepsa\.conda\envs\toolbox37\lib\site-packages\pyreadline\lineeditor\lineobj.py", line 282, in _insert_text
    self.line_buffer.insert(self.point, c)
MemoryError
>>>
```

The fix in my case was

```
pip uninstall pyreadline
```

@manuelma Can we replace pyreadline with something else in `spine_repl.py` so we don't encourage users to install a package that may cause their Python to break?

**Comment by PekkaSavolainen** [comment]
Seems like nobody else is experiencing this problem. It still happens on my system for some unknown reason. I'll close this issue but please drop a line if you see something similar and I'll take a closer look.

**Comment by PekkaSavolainen** [comment]
The solution is to remove `.python_history` file in C:\\Users\\{username}. This file was 3.31 GB on my system.
