### ISSUE TITLE
Toolbox fails (apparently subprocess issue)

### ISSUE THREAD

**Issue by jkiviluo** [Spine-project/Spine-Toolbox#1771]
One of the latest commits (Spine Engine or SpineDB_API) breaks Toolbox for me. I'm on latest Master and I ran `bin\upgrade_spine_reqs.bat`. I get this when starting Toolbox and then also when trying to run anything in the workflow (and nothing works):

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\data\SpineToolbox\src\spine-engine\spine_engine\__init__.py", line 12, in <module>
    from .spine_engine import ExecutionDirection, SpineEngine, SpineEngineState, ItemExecutionFinishState
  File "C:\data\SpineToolbox\src\spine-engine\spine_engine\spine_engine.py", line 53, in <module>
    from .project_item.connection import Connection, Jump
  File "C:\data\SpineToolbox\src\spine-engine\spine_engine\project_item\connection.py", line 25, in <module>
    from spine_engine.project_item.project_item_resource import (
  File "C:\data\SpineToolbox\src\spine-engine\spine_engine\project_item\project_item_resource.py", line 24, in <module>
    from spinedb_api.spine_db_server import closing_spine_db_server
  File "C:\data\SpineToolbox\src\spinedb-api\spinedb_api\spine_db_server.py", line 355, in <module>
    _server_manager = _ServerManager()
  File "C:\data\SpineToolbox\src\spinedb-api\spinedb_api\spine_db_server.py", line 324, in __init__
    self._process.start()
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\prokjt\Miniconda3\envs\spi38\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by soininen** [comment]
I made a quick fix for this. @manuelma, can you check if it's OK?

**Comment by soininen** [comment]
Fixing continued in commit Spine-project/Spine-Database-API@e454af1bfc6d3d784e330dd4875b8426c1975c27

**Comment by manuelma** [comment]
Sorry about this, I could have tested on windows before pushing.

I think @soininen 's fix for the process start/join thing is perfect. I am not sure about the second issue with the None default values, though, I mean I don't understand the issue fully - but if a solution is already in place then thanks @soininen again.

**Comment by soininen** [comment]
> I am not sure about the second issue with the None default values, 

Sorry for scramming two orthogonal fixes in one commit! It has to do with how Merger (and I guess Importer, too) now communicates parameter values over the DB server as using custom `parse_value()` and `unparse_value()`. A bug, yes, but unrelated to this issue at hand. There is still more to come as Merger continues to be broken. I'll open a proper issue for that.

**Comment by jkiviluo** [comment]
Thanks! Seems to work again!

**Comment by manuelma** [comment]
It seems that starting the servers' process on demand is causing new deadlocks because it means the process can be started from different threads. It looks like we need to suppress all sources of concurrency at creating DB servers for things to work. I'm not sure if this is a SQLAlchemy of SQLite limitation or if I'm just wrong.

Anyways, I'm working on a solution that involves starting the server process always from the main process and the main thread, which seems to help. I will test it on windows now.
