### ISSUE TITLE
Traceback in Pivot view

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1784]
I've been trying to catch this slippery eel for several months and finally I think I can reproduce it. I get this Traceback:

```
Traceback (most recent call last):
  File "spinetoolbox\spine_db_signaller.py", line 148, in receive_objects_added
    self._call_in_listeners("receive_objects_added", db_map_data)
  File "spinetoolbox\helpers.py", line 121, in new_function
    return func(*args, **kwargs)
  File "spinetoolbox\spine_db_signaller.py", line 366, in _call_in_listeners
    method({db_map: data})
  File "spinetoolbox\spine_db_editor\widgets\tabular_view_mixin.py", line 834, in receive_objects_added
    self.receive_objects_added_or_removed(db_map_data, action="add")
  File "spinetoolbox\spine_db_editor\widgets\tabular_view_mixin.py", line 757, in receive_objects_added_or_removed
    if self.pivot_table_model.receive_objects_added_or_removed(db_map_data, action):
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 1005, in receive_objects_added_or_removed
    self.receive_data_added_or_removed(data, action)
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 532, in receive_data_added_or_removed
    {"add": self.add_to_model, "remove": self.remove_from_model}[action](db_map_data)
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_table_models.py", line 183, in add_to_model
    row_count, column_count = self.model.add_to_model(db_map_data)
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_model.py", line 91, in add_to_model
    self._row_data_header = self._get_unique_index_values(self.pivot_rows)
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_model.py", line 160, in _get_unique_index_values
    raise e
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_model.py", line 158, in _get_unique_index_values
    result = {index_getter(k): None for k in self._data if frozen_getter(k) == self.frozen_value}
  File "spinetoolbox\spine_db_editor\mvcmodels\pivot_model.py", line 158, in <dictcomp>
    result = {index_getter(k): None for k in self._data if frozen_getter(k) == self.frozen_value}
IndexError: tuple index out of range
```

Something like this seems to happen:
- `TabularViewMixin` thinks `current_class_type == "object_class"`
- Still, Pivot model's `_data` holds relationships with more than one dimension
- We fetch objects
- Objects are added to pivot model's `_data`
- Since `_data` now contains a mixture objects and relationships -> crash

**Comment by soininen** [comment]
I believe I got this fixed.
