### ISSUE TITLE
Importer and exporter broken

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1791]
Executing Exporter (or Importer) in Toolbox gives a Traceback:
```
Process Process-2:
Traceback (most recent call last):
  File "Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "spinedb_api\spine_db_server.py", line 87, in _do_work
    result = handler(*args, **kwargs)
  File "spinedb_api\spine_db_server.py", line 484, in _do_start_server
    _db_manager.open_db_map(server.server_address, db_url, upgrade, memory)
NameError: name '_db_manager' is not defined
```

**Comment by soininen** [comment]
Duplicate of Spine-project/Spine-Database-API#179
