### ISSUE TITLE
Importer tries to commit data instead of canceling on error

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1795]
Importer should bail out and roll back changes when "Cancel import on error" is checked. Instead, a Traceback about failed commit is emitted:
```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "spinedb_api\spine_db_server.py", line 222, in _do_work
    result = handler(*args, **kwargs)
  File "spinedb_api\spine_db_server.py", line 253, in _do_call_method
    result = method(*args, **kwargs)
  File "spinedb_api\db_mapping_commit_mixin.py", line 54, in commit_session
    self._check_commit(comment)
  File "spinedb_api\db_mapping_base.py", line 289, in _check_commit
    raise SpineDBAPIError("Nothing to commit.")
spinedb_api.exception.SpineDBAPIError: Nothing to commit.
```

Reported by @jkiviluo

**Comment by soininen** [comment]
Fixed.
