### ISSUE TITLE
Traceback in Database editor

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1800]
I got the Traceback below after purging "data items" from the database and expanding classes in the relationship tree:

```
Traceback (most recent call last):
  File "spinetoolbox\spine_db_editor\widgets\tabular_view_mixin.py", line 175, in _handle_relationship_tree_selection_changed
    self._handle_entity_tree_current_changed(current)
  File "spinetoolbox\spine_db_editor\widgets\tabular_view_mixin.py", line 178, in _handle_entity_tree_current_changed
    self._update_class_attributes(current_index)
  File "spinetoolbox\spine_db_editor\widgets\tabular_view_mixin.py", line 184, in _update_class_attributes
    current_class_item = self._get_current_class_item(current_index)
  File "spinetoolbox\spine_db_editor\widgets\tabular_view_mixin.py", line 197, in _get_current_class_item
    item = current_index.model().item_from_index(current_index)
AttributeError: 'NoneType' object has no attribute 'item_from_index'
```

**Comment by soininen** [comment]
Fixed.
