### ISSUE TITLE
Changing tool spec type from python to julia breaks the spec

### ISSUE THREAD

**Issue by manuelma** [Spine-project/Spine-Toolbox#1808]
Then, at project loading:
```
Traceback (most recent call last):
  File "/home/manuel/Codes/spine/Spine-Toolbox/spinetoolbox/widgets/custom_menus.py", line 143, in <lambda>
    lambda checked=False, filepath=filepath: self.call_open_project(checked, filepath),
  File "/home/manuel/Codes/spine/Spine-Toolbox/spinetoolbox/widgets/custom_menus.py", line 167, in call_open_project
    if not self._parent.open_project(p):
  File "/home/manuel/Codes/spine/Spine-Toolbox/spinetoolbox/ui_main.py", line 550, in open_project
    return self.restore_project(load_dir)
  File "/home/manuel/Codes/spine/Spine-Toolbox/spinetoolbox/ui_main.py", line 576, in restore_project
    success = self._project.load(self._item_specification_factories, self.item_factories)
  File "/home/manuel/Codes/spine/Spine-Toolbox/spinetoolbox/project.py", line 303, in load
    spec = load_specification_from_file(
  File "/home/manuel/Codes/spine/Spine-Toolbox/spinetoolbox/helpers.py", line 1089, in load_specification_from_file
    spec = specification_from_dict(spec_dict, local_data_dict, spec_factories, app_settings, logger)
  File "/home/manuel/Codes/spine/Spine-Toolbox/spinetoolbox/helpers.py", line 1117, in specification_from_dict
    return spec_factory.make_specification(spec_dict, app_settings, logger)
  File "/home/manuel/Codes/spine/spine-items/spine_items/tool/specification_factory.py", line 34, in make_specification
    return make_specification(definition, app_settings, logger)
  File "/home/manuel/Codes/spine/spine-items/spine_items/tool/tool_specifications.py", line 79, in make_specification
    spec = JuliaTool.load(path, definition, app_settings, logger)
  File "/home/manuel/Codes/spine/spine-items/spine_items/tool/tool_specifications.py", line 465, in load
    return JuliaTool(path=path, settings=settings, logger=logger, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'execution_settings'
```

**Comment by soininen** [comment]
As a workaround, deleting `<project root>/.spinetoolbox/local/specification_local_data.json` should help.

**Comment by soininen** [comment]
Fixed.

**Comment by manuelma** [comment]
Thank you very much @soininen
