### ISSUE TITLE
Traceback from filtering connection if Data store is missing the sqlite file

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1812]
1. Make project with Data store connected some other item
2. Close the project, delete the .sqlite file
3. Open the project, select the connection from Data store

```
Traceback (most recent call last):
  File "spinetoolbox\ui_main.py", line 550, in open_project
    return self.restore_project(load_dir)
  File "spinetoolbox\ui_main.py", line 576, in restore_project
    success = self._project.load(self._item_specification_factories, self.item_factories)
  File "spinetoolbox\project.py", line 317, in load
    self.add_connection(connection, silent=True)
  File "spinetoolbox\project.py", line 735, in add_connection
    self.notify_resource_changes_to_successors(source)
  File "spinetoolbox\project.py", line 1173, in notify_resource_changes_to_successors
    self._update_outgoing_connection_and_jump_resources(item_name, trigger_resources)
  File "spinetoolbox\project.py", line 1177, in _update_outgoing_connection_and_jump_resources
    connection.receive_resources_from_source(trigger_resources)
  File "spinetoolbox\project_item\logging_connection.py", line 324, in receive_resources_from_source
    self.link.update_icons()
  File "spinetoolbox\link.py", line 484, in update_icons
    active = self._connection.has_filters()
  File "spinetoolbox\project_item\logging_connection.py", line 175, in has_filters
    db_map = self._get_db_map(url)
  File "spinetoolbox\project_item\logging_connection.py", line 191, in _get_db_map
    self._toolbox.db_mngr.register_listener(self, db_map)
  File "spinetoolbox\spine_db_manager.py", line 548, in register_listener
    stack = self.undo_stack[db_map]
KeyError: None
```

**Comment by soininen** [comment]
Fixed.
