### ISSUE TITLE
Data connection: Traceback when adding file reference when there are non-existent references

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1814]
I have a project that contains invalid file references in Data connections. When I try to add valid references, I get the following Traceback:
```
Traceback (most recent call last):
  File spine_items\data_connection\data_connection.py", line 183, in show_add_file_references_dialog
    self._add_file_references(file_paths)
  File "spine_items\data_connection\data_connection.py", line 197, in _add_file_references
    if any(os.path.samefile(path, ref) for ref in self.file_references):
  File "spine_items\data_connection\data_connection.py", line 197, in <genexpr>
    if any(os.path.samefile(path, ref) for ref in self.file_references):
  File Python38\lib\genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'xxx.xlsx'
```

We need to check for samefile against a list of existing references.

**Comment by soininen** [comment]
Fixed.
