### ISSUE TITLE
Database Editor's ChangeNotifier tries to notify about database purges after the editor has been closed

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1831]
We should disconnect ChangeNotifiers signals when DB editor is closed. Otherwise purging the database from Data store's Purge button can result in the following Traceback:

```
Traceback (most recent call last):
  File "spinetoolbox\widgets\notification.py", line 238, in _push_notification
    self._notification = ButtonNotification(
  File "spinetoolbox\widgets\notification.py", line 156, in __init__
    super().__init__(*args, **kwargs)
  File "spinetoolbox\widgets\notification.py", line 46, in __init__
    self.setParent(parent)
RuntimeError: Internal C++ object (SpineDBEditor) already deleted.
```

**Comment by soininen** [comment]
Looks like I managed to break something:

```
Traceback (most recent call last):
  File "spinetoolbox\ui_main.py", line 1946, in closeEvent
    self._project.tear_down()
  File "spinetoolbox\project.py", line 1455, in tear_down
    connection.tear_down()
  File "spinetoolbox\project_item\logging_connection.py", line 411, in tear_down
    self._toolbox.db_mngr.unregister_listener(self, db_map)
  File "spinetoolbox\spine_db_manager.py", line 566, in unregister_listener
    self.undo_stack[db_map].indexChanged.disconnect(listener.update_undo_redo_actions)
KeyError: None
```
