### ISSUE TITLE
Toolbox unit tests are broken

### ISSUE THREAD

**Issue by soininen** [Spine-project/Spine-Toolbox#1858]
```
======================================================================
FAIL: test_remove_object_metadata_row (tests.spine_db_editor.mvcmodels.test_item_metadata_table_model.TestItemMetadataTableModelWithExistingData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/Spine-Toolbox/Spine-Toolbox/tests/spine_db_editor/mvcmodels/test_item_metadata_table_model.py", line 280, in test_remove_object_metadata_row
    self.assertEqual(
AssertionError: {<spi[70 chars]: [{'id': 1, 'entity_id': 1, 'metadata_id': 1,[109 chars] 2}]} != {<spi[70 chars]: [{'entity_id': 1, 'id': 1, 'metadata_id': 1,[13 chars] 2}]}
Diff is 1231 characters long. Set self.maxDiff to None to see it.

======================================================================
FAIL: test_remove_object_parameter_value_metadata_row (tests.spine_db_editor.mvcmodels.test_item_metadata_table_model.TestItemMetadataTableModelWithExistingData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/Spine-Toolbox/Spine-Toolbox/tests/spine_db_editor/mvcmodels/test_item_metadata_table_model.py", line 293, in test_remove_object_parameter_value_metadata_row
    self.assertEqual(
AssertionError: {<spi[70 chars]: [{'id': 1, 'parameter_value_id': 1, 'metadat[190 chars] 2}]} != {<spi[70 chars]: [{'parameter_value_id': 1, 'id': 1, 'metadat[22 chars] 2}]}
Diff is 1576 characters long. Set self.maxDiff to None to see it.
````

**Comment by soininen** [comment]
> This can be because I added the commit_id to the item metadata queries?

There's now a lot more information coming from the db map than just commit_id. I got the tests fixed, though. Opening a PR now.
